# -*- coding: utf-8 -*-
# 예비고1 반편성고사 문항 데이터
# 본문 문자열에서 $...$ 는 한글 수식(HWP equation script)
# body: 문단 리스트, box: 조건 상자 문단 리스트(없으면 None), fig: 그림 파일(없으면 None)
# choices: 객관식 5개 수식(단답형은 None), ans: 정답(객관식은 1~5 번호, 단답형은 정수)
# sol: 해설 문단 리스트, src: 변형 원본, unit/level/pts: 단원/난도/배점, point: 평가 요소

PTS = {"하": 3, "중": 5, "상": 6, "최상": 8}

M1 = [
dict(no=1, unit="다항식", level="하", src="2025-3월 7번", point="곱셈 공식의 변형",
 body=["$a-b=3$, $a^{3}-b^{3}=63$ 일 때, $ab$ 의 값은?"],
 choices=["1", "2", "3", "4", "5"], ans=4,
 sol=["$a^{3}-b^{3}= left(a-b right)^{3}+3ab left(a-b right)$ 이므로",
      "$63=27+9ab$ , $9ab=36$",
      "따라서 $ab=4$"]),

dict(no=2, unit="행렬", level="하", src="2026-3월 6번", point="행렬의 성분과 덧셈·실수배",
 body=["이차정사각행렬 $A$ , $B$ 의 $left(i,`j right)$ 성분을 각각 $a_{ij}$ , $b_{ij}$ 라 할 때,",
       "$a_{ij}=2i-j$ , $b_{ij}=ij~ left(i=1,`2,~j=1,`2 right)$",
       "이다. 행렬 $A+2B$ 의 모든 성분의 합은?"],
 choices=["22", "24", "26", "28", "30"], ans=2,
 sol=["$A= left( rpile{ 1 && 0 # 3 && 2 } right)$ , $B= left( rpile{ 1 && 2 # 2 && 4 } right)$ 이므로",
      "$A+2B= left( rpile{ 3 && 4 # 7 && 10 } right)$",
      "따라서 모든 성분의 합은 $3+4+7+10=24$"]),

dict(no=3, unit="방정식과 부등식", level="하", src="2026-3월 7번", point="인수정리를 이용한 삼차방정식의 풀이",
 body=["삼차방정식 $x^{3}-4x^{2}+x+6=0$ 의 모든 양의 실근의 합은?"],
 choices=["3", "4", "5", "6", "7"], ans=3,
 sol=["$x=-1$ 을 대입하면 $-1-4-1+6=0$ 이므로 $x+1$ 은 인수이다.",
      "$x^{3}-4x^{2}+x+6= left(x+1 right) left(x^{2}-5x+6 right)= left(x+1 right) left(x-2 right) left(x-3 right)$",
      "양의 실근은 $2$ , $3$ 이므로 그 합은 $5$"]),

dict(no=4, unit="방정식과 부등식", level="하", src="2025-3월 8번", point="연립이차부등식의 해",
 body=["연립부등식",
       "$cases{ x^{2}-2x-8 ge 0 # x^{2}-36 < 0}$",
       "을 만족시키는 모든 정수 $x$ 의 값의 합은?"],
 choices=["-9", "-8", "-7", "-6", "-5"], ans=5,
 sol=["$x^{2}-2x-8 ge 0$ 에서 $left(x+2 right) left(x-4 right) ge 0$ , 즉 $x le -2$ 또는 $x ge 4$",
      "$x^{2}-36<0$ 에서 $-6<x<6$",
      "공통 범위는 $-6<x le -2$ 또는 $4 le x<6$ 이므로 정수 $x$ 는 $-5,`-4,`-3,`-2,`4,`5$",
      "그 합은 $-14+9=-5$"]),

dict(no=5, unit="다항식", level="중", src="2026-3월 9번", point="나머지정리와 나머지의 결정",
 body=["다항식 $P left(x right)$ 에 대하여 $P left(x+1 right)$ 을 $x$ 로 나눈 나머지는 $5$ 이고, $P left(x-2 right)$ 를 $x+1$ 로 나눈 나머지는 $-3$ 이다. 다항식 $P left(x right)$ 를 $x^{2}+2x-3$ 으로 나눈 나머지를 $R left(x right)$ 라 할 때, $R left(2 right)$ 의 값은?"],
 choices=["7", "9", "11", "13", "15"], ans=1,
 sol=["나머지정리에 의하여 $P left(1 right)=5$ , $P left(-3 right)=-3$",
      "$x^{2}+2x-3= left(x-1 right) left(x+3 right)$ 이므로 $R left(x right)=ax+b$ 라 하면",
      "$P left(x right)= left(x-1 right) left(x+3 right)Q left(x right)+ax+b$",
      "$a+b=5$ , $-3a+b=-3$ 에서 $a=2$ , $b=3$",
      "따라서 $R left(2 right)=2 TIMES 2+3=7$"]),

dict(no=6, unit="행렬", level="중", src="2026-3월 10번", point="행렬의 곱셈과 성분 비교",
 body=["양수 $k$ 에 대하여 두 행렬 $A$ , $B$ 를 각각",
       "$A= left( rpile{ 1 && 2 # k && 3 } right)$ , $B= left( rpile{ k && 2 # -1 && 1 } right)$",
       "라 하자. $AB= left( rpile{ a && 4 # 6 && b } right)$ 일 때, 두 상수 $a$ , $b$ 에 대하여 $a+b$ 의 값은?"],
 choices=["8", "9", "10", "11", "12"], ans=3,
 sol=["$AB= left( rpile{ k-2 && 4 # k^{2}-3 && 2k+3 } right)$",
      "$k^{2}-3=6$ 이고 $k>0$ 이므로 $k=3$",
      "$a=k-2=1$ , $b=2k+3=9$ 이므로 $a+b=10$"]),

dict(no=7, unit="방정식과 부등식", level="중", src="2025-3월 11번", point="켤레복소수의 성질과 복소수의 상등",
 body=["실수가 아닌 복소수 $z$ 에 대하여 $z^{2}=6 { bar{z}}$ 일 때, $z { bar{z}}$ 의 값은? (단, ${ bar{z}}$ 는 $z$ 의 켤레복소수이다.)"],
 choices=["9", "18", "27", "36", "45"], ans=4,
 sol=["$z=x+yi~ left(x,`y 는~실수,~y ne 0 right)$ 라 하면",
      "$z^{2}=x^{2}-y^{2}+2xyi$ , $6{ bar{z}}=6x-6yi$",
      "허수부분에서 $2xy=-6y$ 이고 $y ne 0$ 이므로 $x=-3$",
      "실수부분에서 $9-y^{2}=-18$ 이므로 $y^{2}=27$",
      "따라서 $z{ bar{z}}=x^{2}+y^{2}=9+27=36$"]),

dict(no=8, unit="방정식과 부등식", level="중", src="2025-3월 13번", point="인수분해를 이용한 연립이차방정식",
 body=["연립방정식",
       "$cases{ x^{2}-4xy+3y^{2}=0 # x^{2}-2y^{2}=21}$",
       "의 해를 $x= alpha$ , $y= beta$ 라 할 때, $alpha + beta$ 의 값은? (단, $alpha >0$ , $beta >0$ )"],
 choices=["3 sqrt{3}", "4 sqrt{3}", "5 sqrt{3}", "6 sqrt{3}", "7 sqrt{3}"], ans=2,
 sol=["$x^{2}-4xy+3y^{2}= left(x-y right) left(x-3y right)=0$ 이므로 $x=y$ 또는 $x=3y$",
      "$x=y$ 이면 $-y^{2}=21$ 이 되어 실수해가 없다.",
      "$x=3y$ 이면 $9y^{2}-2y^{2}=21$ , $y^{2}=3$",
      "$alpha >0$ , $beta >0$ 이므로 $beta = sqrt{3}$ , $alpha =3 sqrt{3}$",
      "따라서 $alpha + beta =4 sqrt{3}$"]),

dict(no=9, unit="경우의 수", level="상", src="2025-3월 16번", point="조합을 이용한 경우의 수",
 body=["어느 청소년 센터에서는 서로 다른 $4$ 개의 체육 동아리와 서로 다른 $2$ 개의 음악 동아리를 운영한다. 두 청소년 ${rm{A}}$ 와 ${rm{B}}$ 가 이 $6$ 개의 동아리 중에서 다음 조건을 만족시키도록 동아리를 선택하는 경우의 수는?"],
 box=["(가) ${rm{A}}$ 와 ${rm{B}}$ 는 각자 $1$ 개 이상의 체육 동아리와 $1$ 개 이상의 음악 동아리를 포함한 서로 다른 $3$ 개의 동아리를 선택한다.",
      "(나) ${rm{A}}$ 는 선택하고 ${rm{B}}$ 는 선택하지 않은 동아리의 개수는 적어도 $1$ 이다."],
 choices=["192", "204", "216", "228", "240"], ans=5,
 sol=["(가)를 만족시키도록 $3$ 개의 동아리를 고르는 방법의 수는 전체 ${}_{6} rm C _{3} =20$ 에서 체육 동아리만 $3$ 개 고르는 ${}_{4} rm C _{3} =4$ 를 뺀 $16$ 이다. (음악 동아리는 $2$ 개뿐이므로 음악 동아리만 $3$ 개 고를 수 없다.)",
      "두 사람 모두 $3$ 개씩 고르므로 (나)는 ${rm{A}}$ 와 ${rm{B}}$ 가 고른 동아리의 집합이 서로 다르다는 것과 같다.",
      "따라서 구하는 경우의 수는 $16 TIMES 15=240$"]),

dict(no=10, unit="방정식과 부등식", level="상", src="2026-3월 15번", point="연립이차부등식의 정수해 조건",
 body=["$x$ 에 대한 연립부등식",
       "$cases{ x^{2}-4x-5 ge 0 # left(x+a right) left(x-a+4 right)<0}$",
       "을 만족시키는 정수 $x$ 의 개수가 $6$ 이 되도록 하는 모든 정수 $a$ 의 값의 합은?"],
 choices=["4", "5", "6", "7", "8"], ans=1,
 sol=["$x^{2}-4x-5 ge 0$ 에서 $x le -1$ 또는 $x ge 5$",
      "$left(x+a right) left(x-a+4 right)<0$ 의 해는 두 수 $-a$ , $a-4$ 사이의 범위이고, 두 수의 중점은 $-2$ 이므로 $d= left| a-2 right|$ 라 하면 해는 $-2-d<x<-2+d$",
      "$d ge 8$ 이면 $-9,`-8,` CDOTS ,`-1$ 이 모두 해가 되어 정수가 $9$ 개 이상이다.",
      "$d le 7$ 이면 $-2+d le 5$ 이므로 $x ge 5$ 인 해는 없고, $x le -1$ 인 정수만 센다. 이 정수가 $6$ 개, 즉 $-6,`-5,` CDOTS ,`-1$ 이려면 $-7 le -2-d<-6$ 이므로 $4<d le 5$",
      "$a$ 가 정수이므로 $d=5$ 이고, $left| a-2 right|=5$ 에서 $a=7$ 또는 $a=-3$",
      "따라서 모든 정수 $a$ 의 값의 합은 $4$"]),

dict(no=11, unit="경우의 수", level="상", src="2026-3월 16번", point="조건이 있는 분배의 경우의 수",
 body=["서로 다른 동화책 $2$ 권, 서로 다른 시집 $4$ 권이 있다. 이 $6$ 권의 책을 다음 규칙에 따라 $1$ 학년 학생 $2$ 명과 $2$ 학년 학생 $3$ 명에게 남김없이 나누어 주는 경우의 수는? (단, $5$ 명의 학생 중 책을 한 권도 받지 못하는 학생은 없다.)"],
 box=["(가) 동화책은 $2$ 학년 학생에게만 나누어 준다.",
      "(나) 시집을 $2$ 권 이상 받는 학생은 없다."],
 choices=["288", "312", "336", "360", "384"], ans=4,
 sol=["$6$ 권을 $5$ 명에게 모두 $1$ 권 이상 주므로 한 명이 $2$ 권, 나머지 $4$ 명이 $1$ 권씩 받는다. (나)에 의하여 $2$ 권 받는 학생은 동화책을 $1$ 권 이상 받으므로 $2$ 학년이다.",
      "(i) 한 $2$ 학년 학생이 동화책 $2$ 권을 받는 경우: 학생 선택 $3$ 가지, 나머지 $4$ 명에게 시집을 $1$ 권씩 주는 $4!=24$ 가지이므로 $3 TIMES 24=72$",
      "(ii) 한 $2$ 학년 학생이 동화책 $1$ 권과 시집 $1$ 권을 받는 경우: 이 학생 선택 $3$ 가지, 받을 동화책 $2$ 가지, 남은 동화책을 받을 다른 $2$ 학년 학생 $2$ 가지, 시집 $4$ 권을 남은 $4$ 개의 자리에 $1$ 권씩 주는 $4!=24$ 가지이므로 $3 TIMES 2 TIMES 2 TIMES 24=288$",
      "따라서 구하는 경우의 수는 $72+288=360$"]),

dict(no=12, unit="방정식과 부등식", level="상", src="2025-3월 17번", point="이차방정식의 근과 서로 다른 실근의 개수",
 body=["이차함수 $f left(x right)=x^{2}-3x-4$ 가 있다. 실수 $k$ 에 대하여 $x$ 에 대한 방정식 $f left(x right)f left(x-k right)=0$ 의 서로 다른 실근의 개수를 $g left(k right)$ 라 하자. $g left(k-6 right)+g left(k+4 right)=6$ 이 되도록 하는 모든 $k$ 의 값의 합은?"],
 choices=["1", "2", "3", "4", "5"], ans=3,
 sol=["$f left(x right)= left(x+1 right) left(x-4 right)$ 이므로 $f left(x right)=0$ 의 근은 $-1$ , $4$ 이고, $f left(x-k right)=0$ 의 근은 $k-1$ , $k+4$ 이다.",
      "따라서 $g left(k right)=2~ left(k=0 right)$ , $g left(k right)=3~ left(k=5~또는~k=-5 right)$ , 그 외에는 $g left(k right)=4$",
      "합이 $6$ 이 되는 경우는 $left(2,`4 right)$ , $left(4,`2 right)$ , $left(3,`3 right)$ 이다.",
      "(i) $g left(k-6 right)=2$ : $k=6$ 이고 $g left(10 right)=4$ 이므로 성립",
      "(ii) $g left(k+4 right)=2$ : $k=-4$ 이고 $g left(-10 right)=4$ 이므로 성립",
      "(iii) $k-6$ 과 $k+4$ 가 모두 $5$ 또는 $-5$ : 두 수의 차가 $10$ 이므로 $k-6=-5$ , $k+4=5$ , 즉 $k=1$",
      "따라서 모든 $k$ 의 값의 합은 $6+ left(-4 right)+1=3$"]),

dict(no=13, unit="경우의 수", level="상", src="2025-3월 18번", point="조건을 만족시키는 배열의 경우의 수",
 body=["어느 숙소에는 그림과 같이 객실 번호가 적힌 $10$ 개의 객실이 있다."],
 fig="room.png",
 body2=["관광객 ${rm{A}}$ , ${rm{B}}$ , ${rm{C}}$ 를 포함한 $5$ 명의 관광객이 다음 규칙에 따라 $10$ 개의 객실 중에서 각자 서로 다른 한 객실에 숙박하는 경우의 수는?"],
 box=["(가) $5$ 명의 관광객 중 어느 관광객도 객실 번호가 $102$ , $204$ 인 객실에는 숙박하지 않는다.",
      "(나) ${rm{A}}$ 와 ${rm{B}}$ 가 숙박하는 객실 번호의 차는 $1$ 이다.",
      "(다) ${rm{A}}$ 와 ${rm{C}}$ 가 숙박하는 객실 번호의 차는 $4$ 보다 크고 $100$ 이 아니다."],
 choices=["520", "560", "600", "640", "680"], ans=2,
 sol=["숙박 가능한 객실은 $1$ 층 $101,`103,`104,`105$ , $2$ 층 $201,`202,`203,`205$ 이다.",
      "(나)에서 ${rm{A}}$ , ${rm{B}}$ 는 같은 층의 번호가 연속인 두 객실이므로 $left{103,`104 right}$ , $left{104,`105 right}$ , $left{201,`202 right}$ , $left{202,`203 right}$ 중 하나이다.",
      "(다)에서 같은 층의 두 객실 번호의 차는 $4$ 이하이므로 ${rm{C}}$ 는 ${rm{A}}$ 와 다른 층에 있고, ${rm{A}}$ 의 바로 위 또는 아래 객실은 제외한다.",
      "${rm{A}}$ 의 객실이 $103$ , $104$ , $104$ , $105$ , $201$ , $202$ , $202$ , $203$ 인 $8$ 가지 경우에 ${rm{C}}$ 의 객실의 수는 각각 $3,`4,`4,`3,`3,`4,`4,`3$ 이므로 합은 $28$ ( $104$ , $202$ 는 바로 위·아래 객실이 숙박 금지 객실이다.)",
      "남은 $2$ 명은 남은 $5$ 개의 객실 중 $2$ 개에 숙박하므로 ${}_{5} rm P _{2} =20$",
      "따라서 구하는 경우의 수는 $28 TIMES 20=560$"]),

dict(no=14, unit="방정식과 부등식", level="최상", src="2026-3월 18번", point="이차함수의 그래프와 방정식의 실근의 개수",
 body=["최고차항의 계수가 $1$ 인 이차함수 $f left(x right)$ 가 있다. $x$ 에 대한 방정식",
       "$f left(x right) TIMES left{f left(x right)+2f left(t right) right}=0$",
       "의 서로 다른 실근의 개수가 $3$ 이 되도록 하는 모든 실수 $t$ 의 값이 $-1$ , $5$ 일 때, $f left(8 right)$ 의 값은?"],
 choices=["22", "24", "26", "28", "30"], ans=5,
 sol=["$f left(x right)= left(x-p right)^{2}+q$ 라 하자. 주어진 방정식은 $f left(x right)=0$ 또는 $f left(x right)=-2f left(t right)$ 이다.",
      "$q>0$ 이면 $f left(x right)=0$ 은 실근이 없으므로 실근은 $2$ 개 이하이다. $q=0$ 이면 $f left(x right)=0$ 의 근은 $p$ 하나이고, $left(x-p right)^{2}=-2 left(t-p right)^{2}$ 은 $x=p$ 외의 근이 없으므로 실근은 $1$ 개이다. 따라서 $q<0$",
      "$q<0$ 이면 $f left(x right)=0$ 은 서로 다른 두 실근을 가진다. $f left(t right)=0$ 이면 두 방정식이 같아 실근은 $2$ 개이므로, 실근이 $3$ 개가 되려면 $f left(x right)=-2f left(t right)$ 가 중근을 가져야 한다.",
      "$left(x-p right)^{2}=-q-2f left(t right)$ 가 중근을 가지려면 $-q-2 left{ left(t-p right)^{2}+q right}=0$ , 즉 $left(t-p right)^{2}=-{3} over {2}q$",
      "이를 만족시키는 $t$ 는 $p PLUSMINUS sqrt{-{3} over {2}q}$ 이므로 $p={-1+5} over {2}=2$ , $-{3} over {2}q=9$ 에서 $q=-6$",
      "$f left(x right)= left(x-2 right)^{2}-6$ 이므로 $f left(8 right)=36-6=30$"]),

dict(no=15, unit="방정식과 부등식", level="하", src="2026-3월 24번", point="근과 계수의 관계",
 body=["$x$ 에 대한 이차방정식 $x^{2}-ax+6=0$ 이 서로 다른 두 근 $alpha$ , $beta$ 를 갖는다. ${1} over {alpha} + {1} over {beta} = {3} over {2}$ 일 때, $alpha^{2}+ beta^{2}$ 의 값을 구하시오. (단, $a$ 는 상수이다.)"],
 choices=None, ans=69,
 sol=["근과 계수의 관계에 의하여 $alpha + beta =a$ , $alpha beta =6$",
      "${1} over {alpha} + {1} over {beta} = {alpha + beta} over {alpha beta} = {a} over {6} = {3} over {2}$ 이므로 $a=9$",
      "$alpha^{2}+ beta^{2}= left( alpha + beta right)^{2}-2 alpha beta =81-12=69$"]),

dict(no=16, unit="방정식과 부등식", level="하", src="2025-3월 24번", point="계수가 실수인 이차방정식의 허근",
 body=["두 실수 $a$ , $b$ 에 대하여 이차방정식 $x^{2}+ax+b=0$ 의 한 근이 $3-i$ 일 때, $a^{2}+b^{2}$ 의 값을 구하시오. (단, $i= sqrt{-1}$ )"],
 choices=None, ans=136,
 sol=["계수가 실수이므로 다른 한 근은 $3+i$ 이다.",
      "두 근의 합 $6=-a$ , 두 근의 곱 $left(3-i right) left(3+i right)=10=b$",
      "$a=-6$ , $b=10$ 이므로 $a^{2}+b^{2}=36+100=136$"]),

dict(no=17, unit="경우의 수", level="중", src="2026-3월 27번", point="조건을 만족시키는 자리 배정의 경우의 수",
 body=["그림과 같이 좌석 번호가 적힌 $8$ 개의 의자가 배열되어 있다."],
 fig="chair.png",
 body2=["네 학생 ${rm{A}}$ , ${rm{B}}$ , ${rm{C}}$ , ${rm{D}}$ 가 다음 규칙에 따라 $8$ 개의 의자 중에서 서로 다른 $4$ 개의 의자에 앉는 경우의 수를 구하시오."],
 box=["(가) ${rm{A}}$ 가 앉는 의자의 좌석 번호는 짝수이다.",
      "(나) ${rm{B}}$ 가 앉는 의자의 좌석 번호는 $22$ 이하이다.",
      "(다) ${rm{C}}$ 와 ${rm{D}}$ 가 앉는 두 의자의 좌석 번호는 각각 $31$ 이상이다."],
 choices=None, ans=120,
 sol=["${rm{C}}$ , ${rm{D}}$ 는 $31,`32,`41,`42$ 중에서, ${rm{B}}$ 는 $11,`12,`21,`22$ 중에서 앉는다.",
      "(i) ${rm{A}}$ 가 $12$ 또는 $22$ 에 앉는 경우: ${rm{A}}$ $2$ 가지, ${rm{B}}$ 는 남은 $3$ 가지, ${rm{C}}$ , ${rm{D}}$ 는 ${}_{4} rm P _{2} =12$ 가지이므로 $2 TIMES 3 TIMES 12=72$",
      "(ii) ${rm{A}}$ 가 $32$ 또는 $42$ 에 앉는 경우: ${rm{A}}$ $2$ 가지, ${rm{B}}$ $4$ 가지, ${rm{C}}$ , ${rm{D}}$ 는 남은 $3$ 개 중 ${}_{3} rm P _{2} =6$ 가지이므로 $2 TIMES 4 TIMES 6=48$",
      "따라서 구하는 경우의 수는 $72+48=120$"]),

dict(no=18, unit="방정식과 부등식", level="중", src="2025-3월 6번", point="이차함수의 그래프와 직선의 위치 관계",
 body=["이차함수 $y=x^{2}+ax+3a-4$ 의 그래프가 직선 $y=2x-1$ 에 접하도록 하는 모든 실수 $a$ 의 값의 합을 구하시오."],
 choices=None, ans=16,
 sol=["$x^{2}+ax+3a-4=2x-1$ 에서 $x^{2}+ left(a-2 right)x+3a-3=0$",
      "접하려면 판별식 $D= left(a-2 right)^{2}-4 left(3a-3 right)=a^{2}-16a+16=0$",
      "이 이차방정식의 판별식이 $16^{2}-4 TIMES 16>0$ 이므로 서로 다른 두 실근을 갖고, 근과 계수의 관계에 의하여 모든 $a$ 의 값의 합은 $16$"]),

dict(no=19, unit="행렬", level="상", src="2026-3월 29번", point="행렬의 곱셈과 성분 조건의 추론",
 body=["영행렬이 아닌 두 행렬 $A= left( rpile{ a_{11} && a_{12} # a_{21} && a_{22} } right)$ , $B= left( rpile{ b_{11} && b_{12} # b_{21} && b_{22} } right)$ 는 $A^{2}=B$ 이고, 각 행렬의 성분은 다음 조건을 만족시킨다."],
 box=["(가) 모든 $i$ , $j~ left(i=1,`2,~j=1,`2 right)$ 에 대하여 $a_{ij} TIMES b_{ij}=0$ 이다.",
      "(나) 모든 $i$ , $j~ left(i=1,`2,~j=1,`2 right)$ 에 대하여 $a_{ij}+b_{ij} ne 0$ 이다."],
 body2=["행렬 $A+B$ 의 모든 성분의 합이 $2$ , 곱이 $-1$ 일 때, $a_{12}^{3}+a_{21}^{3}$ 의 값을 구하시오. (단, $A^{2}=AA$ 이고, 행렬 $A$ 의 모든 성분은 실수이다.)"],
 choices=None, ans=76,
 sol=["$A= left( rpile{ a && b # c && d } right)$ 라 하면 $A^{2}= left( rpile{ a^{2}+bc && b left(a+d right) # c left(a+d right) && d^{2}+bc } right)$",
      "$b=0$ 이면 $b_{12}=0$ 이 되어 (나)에 모순이므로 $b ne 0$ , 같은 방법으로 $c ne 0$ . (가)에서 $b left(a+d right)=0$ 이므로 $a+d=0$",
      "이때 $B= left( rpile{ a^{2}+bc && 0 # 0 && a^{2}+bc } right)$ 이고, $a ne 0$ 이면 (가)에서 $a^{2}+bc=0$ , 즉 $B=O$ 이므로 모순. 따라서 $a=d=0$",
      "$A+B= left( rpile{ bc && b # c && bc } right)$ 이므로 성분의 곱 $left(bc right)^{3}=-1$ 에서 $bc=-1$",
      "성분의 합 $2bc+b+c=2$ 에서 $b+c=4$",
      "$a_{12}^{3}+a_{21}^{3}=b^{3}+c^{3}= left(b+c right)^{3}-3bc left(b+c right)=64+12=76$"]),

dict(no=20, unit="다항식", level="최상", src="2026-3월 20번", point="다항식의 나눗셈과 인수의 추론",
 body=["최고차항의 계수가 $1$ 인 서로 다른 세 이차다항식 $f left(x right)$ , $g left(x right)$ , $h left(x right)$ 가 다음 조건을 만족시킨다."],
 box=["(가) 다항식 $f left(x right)g left(x right)$ 는 다항식 $left(x+1 right)h left(x right)$ 로 나누어떨어진다.",
      "(나) 다항식 $g left(x right)h left(x right)$ 는 다항식 $left(x-3 right)f left(x right)$ 로 나누어떨어진다."],
 body2=["$f left(1 right)+g left(1 right)=-12$ 일 때, $h left(0 right)$ 의 값을 구하시오."],
 choices=None, ans=15,
 sol=["차수를 비교하면 최고차항의 계수가 $1$ 인 일차식 $P left(x right)$ , $Q left(x right)$ 에 대하여",
      "$f left(x right)g left(x right)= left(x+1 right)h left(x right)P left(x right)$ , $g left(x right)h left(x right)= left(x-3 right)f left(x right)Q left(x right)$",
      "두 식을 변끼리 곱하면 $left{g left(x right) right}^{2}= left(x+1 right) left(x-3 right)P left(x right)Q left(x right)$",
      "좌변의 각 근은 중근이므로 $left{P,`Q right}= left{x+1,`x-3 right}$ 이고 $g left(x right)= left(x+1 right) left(x-3 right)$",
      "$P left(x right)=x-3$ 이면 첫 식에서 $f left(x right)=h left(x right)$ 가 되어 모순이므로 $P left(x right)=x+1$ , 즉 $f left(x right) left(x-3 right)=h left(x right) left(x+1 right)$",
      "따라서 $f left(x right)= left(x+1 right) left(x-u right)$ , $h left(x right)= left(x-3 right) left(x-u right)$ 꼴이다.",
      "$f left(1 right)+g left(1 right)=2 left(1-u right)-4=-12$ 에서 $u=5$",
      "$h left(0 right)= left(-3 right) TIMES left(-5 right)=15$"]),
]

M2 = [
dict(no=1, unit="도형의 방정식", level="하", src="2026-3월 5번", point="수직인 두 직선의 기울기",
 body=["두 점 $left(1,`2 right)$ , $left(3,`8 right)$ 을 지나는 직선에 수직이고 점 $left(3,`1 right)$ 을 지나는 직선의 $y$ 절편은?"],
 choices=["1", "2", "3", "4", "5"], ans=2,
 sol=["두 점을 지나는 직선의 기울기는 ${8-2} over {3-1} =3$ 이므로 수직인 직선의 기울기는 $-{1} over {3}$",
      "점 $left(3,`1 right)$ 을 지나므로 $y-1=-{1} over {3} left(x-3 right)$ , 즉 $y=-{1} over {3}x+2$",
      "따라서 $y$ 절편은 $2$"]),

dict(no=2, unit="함수와 그래프", level="하", src="2026-3월 4번", point="대응 관계와 합성함수·역함수의 값",
 body=["그림은 함수 $f`:`X rarrow X$ 를 나타낸 것이다."],
 fig="mapping.png",
 body2=["$left(f circ f right) left(1 right)+f^{-1} left(5 right)$ 의 값은?"],
 choices=["2", "3", "4", "5", "6"], ans=4,
 sol=["그림에서 $f left(1 right)=4$ , $f left(4 right)=2$ 이므로 $left(f circ f right) left(1 right)=f left(4 right)=2$",
      "$f left(3 right)=5$ 이므로 $f^{-1} left(5 right)=3$",
      "따라서 구하는 값은 $2+3=5$"]),

dict(no=3, unit="함수와 그래프", level="하", src="2025-3월 5번", point="역함수의 성질",
 body=["일차함수 $f left(x right)=ax-3$ 의 역함수 $f^{-1} left(x right)$ 에 대하여 $f^{-1} left(5 right)=2$ 일 때, $f^{-1} left(13 right)$ 의 값은? (단, $a$ 는 상수이다.)"],
 choices=["4", "5", "6", "7", "8"], ans=1,
 sol=["$f^{-1} left(5 right)=2$ 이므로 $f left(2 right)=2a-3=5$ , $a=4$",
      "$f^{-1} left(13 right)=k$ 라 하면 $f left(k right)=4k-3=13$ 이므로 $k=4$"]),

dict(no=4, unit="도형의 방정식", level="하", src="2026-3월 23번", point="삼각형의 무게중심",
 body=["좌표평면 위의 세 점 ${rm{A}} left(1,`4 right)$ , ${rm{B}} left(a,`-2 right)$ , ${rm{C}} left(5,`b right)$ 에 대하여 삼각형 ${rm{ABC}}$ 의 무게중심의 좌표가 $left(3,`2 right)$ 일 때, $a+b$ 의 값은?"],
 choices=["5", "6", "7", "8", "9"], ans=3,
 sol=["${1+a+5} over {3} =3$ 에서 $a=3$ , ${4+ left(-2 right)+b} over {3} =2$ 에서 $b=4$",
      "따라서 $a+b=7$"]),

dict(no=5, unit="도형의 방정식", level="중", src="2025-3월 9번", point="도형의 평행이동과 대칭이동",
 body=["직선 $y=ax+3$ 을 $x$ 축의 방향으로 $2$ 만큼, $y$ 축의 방향으로 $-1$ 만큼 평행이동한 후, $x$ 축에 대하여 대칭이동한 직선이 원 $x^{2}+y^{2}+2x-8y+8=0$ 의 넓이를 이등분할 때, 상수 $a$ 의 값은?"],
 choices=["-2", "-1", "0", "1", "2"], ans=5,
 sol=["평행이동한 직선은 $y+1=a left(x-2 right)+3$ , 즉 $y=a left(x-2 right)+2$",
      "$x$ 축에 대하여 대칭이동하면 $-y=a left(x-2 right)+2$ , 즉 $y=-a left(x-2 right)-2$",
      "원 $left(x+1 right)^{2}+ left(y-4 right)^{2}=9$ 의 넓이를 이등분하려면 중심 $left(-1,`4 right)$ 를 지나야 하므로",
      "$4=-a left(-3 right)-2$ , $3a=6$ , $a=2$"]),

dict(no=6, unit="집합과 명제", level="중", src="2026-3월 11번", point="충분조건과 진리집합의 포함 관계",
 body=["실수 $x$ 에 대한 두 조건",
       "$p`:` left| x-a right| >3$ ,",
       "$q`:`x^{2}-6x+8 le 0$",
       "이 있다. $q$ 가 $~ sim p$ 이기 위한 충분조건이 되도록 하는 모든 정수 $a$ 의 값의 합은?"],
 choices=["12", "15", "18", "21", "24"], ans=2,
 sol=["$q$ 의 진리집합은 $Q= left{x left| 2 le x le 4 right. right}$",
      "$sim p`:` left| x-a right| le 3$ 의 진리집합은 $left{x left| a-3 le x le a+3 right. right}$",
      "$Q$ 가 이 집합에 포함되어야 하므로 $a-3 le 2$ , $a+3 ge 4$ , 즉 $1 le a le 5$",
      "정수 $a$ 는 $1,`2,`3,`4,`5$ 이므로 합은 $15$"]),

dict(no=7, unit="함수와 그래프", level="중", src="2026-3월 8번", point="유리함수의 최댓값과 최솟값",
 body=["$2 le x le 4$ 에서 함수 $f left(x right)={a} over {x+1} +b~ left(a<0 right)$ 의 최댓값이 $3$ , 최솟값이 $1$ 일 때, 두 상수 $a$ , $b$ 에 대하여 $a+b$ 의 값은?"],
 choices=["-11", "-10", "-9", "-8", "-7"], ans=3,
 sol=["$a<0$ 이므로 $2 le x le 4$ 에서 $f left(x right)$ 는 $x$ 의 값이 커지면 함숫값도 커진다.",
      "최댓값 $f left(4 right)={a} over {5} +b=3$ , 최솟값 $f left(2 right)={a} over {3} +b=1$",
      "두 식을 빼면 $-{2a} over {15} =2$ , $a=-15$ 이고 $b=6$",
      "따라서 $a+b=-9$"]),

dict(no=8, unit="도형의 방정식", level="중", src="2025-3월 12번", point="원 위의 점과 직선 사이의 거리",
 body=["좌표평면 위에 원 $C`:`x^{2}+y^{2}+2x-4y+1=0$ 이 있다. 두 점 ${rm{A}} left(1,`-3 right)$ , ${rm{B}} left(4,`1 right)$ 과 원 $C$ 위의 점 ${rm{P}}$ 에 대하여 삼각형 ${rm{PAB}}$ 의 넓이의 최댓값은?"],
 choices=["{33} over {2}", "17", "{35} over {2}", "18", "{37} over {2}"], ans=1,
 sol=["원 $C$ 는 중심이 $left(-1,`2 right)$ , 반지름의 길이가 $2$ 인 원이다.",
      "직선 ${rm{AB}}$ 의 방정식은 $4x-3y-13=0$ 이고 ${ bar{rm{AB}}} = sqrt{9+16} =5$",
      "원의 중심과 직선 ${rm{AB}}$ 사이의 거리는 ${ left| -4-6-13 right|} over {5} = {23} over {5}$",
      "점 ${rm{P}}$ 와 직선 ${rm{AB}}$ 사이의 거리의 최댓값은 ${23} over {5} +2= {33} over {5}$",
      "따라서 넓이의 최댓값은 ${1} over {2} TIMES 5 TIMES {33} over {5} = {33} over {2}$"]),

dict(no=9, unit="함수와 그래프", level="상", src="2025-3월 10번", point="무리함수의 그래프와 도형의 넓이",
 body=["그림과 같이 양수 $k$ 에 대하여 함수 $f left(x right)= sqrt{2x}$ 의 그래프 위의 두 점 ${rm{A}} left(k,`f left(k right) right)$ , ${rm{B}} left(9k,`f left(9k right) right)$ 에서 $x$ 축에 내린 수선의 발을 각각 ${rm{C}}$ , ${rm{D}}$ 라 하자. 사각형 ${rm{ACDB}}$ 의 넓이가 $64$ 일 때, ${ bar{rm{AB}}}$ 의 값은?"],
 fig="sqrt.png",
 choices=["4 sqrt{15}", "6 sqrt{7}", "2 sqrt{65}", "4 sqrt{17}", "12 sqrt{2}"], ans=4,
 sol=["${ bar{rm{AC}}} = sqrt{2k}$ , ${ bar{rm{BD}}} = sqrt{18k} =3 sqrt{2k}$ , ${ bar{rm{CD}}} =8k$",
      "사다리꼴 ${rm{ACDB}}$ 의 넓이는 ${1} over {2} TIMES 4 sqrt{2k} TIMES 8k=16k sqrt{2k} =64$ 이므로 $k sqrt{2k} =4$",
      "양변을 제곱하면 $2k^{3}=16$ , $k=2$",
      "${rm{A}} left(2,`2 right)$ , ${rm{B}} left(18,`6 right)$ 이므로 ${ bar{rm{AB}}} = sqrt{16^{2}+4^{2}} = sqrt{272} =4 sqrt{17}$"]),

dict(no=10, unit="집합과 명제", level="상", src="2025-3월 15번", point="필요조건과 진리집합의 포함 관계",
 body=["실수 $x$ 에 대한 두 조건",
       "$p`:` left(x-2a right) left(x+a right)>0$ ,",
       "$q`:` left| x-1 right| le 5$",
       "가 있다. $q$ 가 $~ sim p$ 이기 위한 필요조건이 되도록 하는 실수 $a$ 의 최댓값을 $M$ , 최솟값을 $m$ 이라 할 때, $Mm$ 의 값은?"],
 choices=["-10", "-9", "-8", "-7", "-6"], ans=5,
 sol=["$q$ 의 진리집합은 $Q= left{x left| -4 le x le 6 right. right}$ 이고, $sim p`:` left(x-2a right) left(x+a right) le 0$ 의 진리집합을 $P^{C}$ 라 하면 $P^{C} subset Q$ 이어야 한다.",
      "(i) $a>0$ 일 때 $P^{C}= left{x left| -a le x le 2a right. right}$ 이므로 $-a ge -4$ , $2a le 6$ 에서 $0<a le 3$",
      "(ii) $a=0$ 일 때 $P^{C}= left{0 right}$ 이므로 성립",
      "(iii) $a<0$ 일 때 $P^{C}= left{x left| 2a le x le -a right. right}$ 이므로 $2a ge -4$ , $-a le 6$ 에서 $-2 le a<0$",
      "따라서 $-2 le a le 3$ 이므로 $M=3$ , $m=-2$ , $Mm=-6$"]),

dict(no=11, unit="도형의 방정식", level="상", src="2026-3월 14번", point="대칭이동을 이용한 거리의 최솟값",
 body=["그림과 같이 좌표평면 위에 원 $C`:` left(x-10 right)^{2}+ left(y-6 right)^{2}=5$ 와 점 ${rm{A}} left(1,`0 right)$ 이 있다. 원 $C$ 위의 점 ${rm{P}}$ , 직선 $y=x$ 위의 점 ${rm{Q}}$ 에 대하여 ${ bar{rm{AQ}}} + { bar{rm{QP}}}$ 의 최솟값은?"],
 fig="reflect.png",
 choices=["3 sqrt{5}", "4 sqrt{5}", "5 sqrt{5}", "6 sqrt{5}", "7 sqrt{5}"], ans=2,
 sol=["점 ${rm{A}}$ 를 직선 $y=x$ 에 대하여 대칭이동한 점을 ${rm{A}} prime$ 이라 하면 ${rm{A}} prime left(0,`1 right)$ 이고 ${ bar{rm{AQ}}} = { bar{{rm{A}} prime {rm{Q}}}}$",
      "${ bar{rm{AQ}}} + { bar{rm{QP}}} = { bar{{rm{A}} prime {rm{Q}}}} + { bar{rm{QP}}} ge { bar{{rm{A}} prime {rm{P}}}}$",
      "원의 중심 $left(10,`6 right)$ 과 ${rm{A}} prime$ 사이의 거리는 $sqrt{100+25} =5 sqrt{5}$ 이므로 ${ bar{{rm{A}} prime {rm{P}}}}$ 의 최솟값은 $5 sqrt{5} - sqrt{5} =4 sqrt{5}$",
      "점 ${rm{A}} prime$ 과 원 $C$ 는 직선 $y=x$ 에 대하여 서로 반대쪽에 있으므로 이때의 선분 ${rm{A}} prime {rm{P}}$ 는 직선 $y=x$ 와 만난다. 따라서 구하는 최솟값은 $4 sqrt{5}$"]),

dict(no=12, unit="함수와 그래프", level="상", src="2025-3월 14번", point="유리함수의 그래프와 최댓값",
 body=["$0 le x le 2$ 에서 함수 $f left(x right)={2x+k} over {x-3}$ 의 최댓값이 $4$ 가 되도록 하는 상수 $k$ 의 값은?"],
 choices=["-11", "-10", "-9", "-8", "-7"], ans=4,
 sol=["$f left(x right)=2+ {k+6} over {x-3}$",
      "(i) $k+6>0$ 이면 $0 le x le 2$ 에서 감소하므로 최댓값은 $f left(0 right)=2- {k+6} over {3} =4$ 에서 $k=-12$ 인데 $k+6>0$ 에 모순",
      "(ii) $k+6<0$ 이면 증가하므로 최댓값은 $f left(2 right)=2- left(k+6 right)=4$ 에서 $k=-8$ (조건 만족)",
      "(iii) $k+6=0$ 이면 $f left(x right)=2$ 이므로 성립하지 않는다.",
      "따라서 $k=-8$"]),

dict(no=13, unit="함수와 그래프", level="상", src="2026-3월 12번", point="무리함수와 역함수의 그래프의 교점",
 body=["그림과 같이 함수 $f left(x right)=3 sqrt{x}$ 의 그래프와 함수 $g left(x right)={1} over {9} x^{2}~ left(x ge 0 right)$ 의 그래프가 만나는 두 점 중 원점 ${rm{O}}$ 가 아닌 점을 ${rm{A}}$ 라 하고, 선분 ${rm{OA}}$ 를 $4`:`5$ 로 내분하는 점을 ${rm{P}}$ 라 하자. 점 ${rm{P}}$ 를 지나고 $x$ 축에 평행한 직선이 두 곡선 $y=f left(x right)$ , $y=g left(x right)$ 와 만나는 점을 각각 ${rm{B}}$ , ${rm{C}}$ 라 할 때, 삼각형 ${rm{ABC}}$ 의 넓이는?"],
 fig="twocurve.png",
 choices=["{89} over {9}", "{92} over {9}", "{95} over {9}", "{98} over {9}", "{101} over {9}"], ans=3,
 sol=["$3 sqrt{x} = {1} over {9} x^{2}$ 에서 $x^{4}=729x$ , $x left(x^{3}-729 right)=0$ 이므로 ${rm{A}} left(9,`9 right)$",
      "${rm{P}}$ 는 선분 ${rm{OA}}$ 를 $4`:`5$ 로 내분하므로 ${rm{P}} left(4,`4 right)$",
      "$3 sqrt{x} =4$ 에서 $x= {16} over {9}$ 이므로 ${rm{B}} left({16} over {9},`4 right)$ , ${1} over {9} x^{2}=4$ 에서 $x=6$ 이므로 ${rm{C}} left(6,`4 right)$",
      "${ bar{rm{BC}}} =6- {16} over {9} = {38} over {9}$ 이고 높이는 $9-4=5$ 이므로 넓이는 ${1} over {2} TIMES {38} over {9} TIMES 5= {95} over {9}$"]),

dict(no=14, unit="도형의 방정식", level="최상", src="2026-3월 17번", point="원과 직선의 위치 관계와 거리 비",
 body=["그림과 같이 좌표평면 위에 원 $C`:` left(x-4 right)^{2}+ left(y-2 right)^{2}=4$ 와 직선 $y=mx~ left(0<m<1 right)$ 이 있다. 원 $C$ 의 중심을 ${rm{A}}$ , 점 ${rm{A}}$ 에서 직선 $y=mx$ 에 내린 수선의 발을 ${rm{H}}$ , 직선 $y=mx$ 가 원 $C$ 와 만나는 두 점 중 원점 ${rm{O}}$ 에 가까운 점을 ${rm{B}}$ 라 할 때, ${ bar{rm{OH}}} `:` { bar{rm{BH}}} =3`:`1$ 이다. 상수 $m$ 의 값은?"],
 fig="circleline.png",
 choices=["{1} over {7}", "{1} over {6}", "{1} over {5}", "{1} over {4}", "{1} over {3}"], ans=1,
 sol=["${ bar{rm{AH}}} =d$ 라 하면 ${ bar{rm{OA}}}^{2} =16+4=20$ 이므로 ${ bar{rm{OH}}}^{2} =20-d^{2}$ , ${ bar{rm{BH}}}^{2} =4-d^{2}$",
      "${ bar{rm{OH}}} =3 { bar{rm{BH}}}$ 이므로 $20-d^{2}=9 left(4-d^{2} right)$ , $d^{2}=2$",
      "점 ${rm{A}} left(4,`2 right)$ 와 직선 $mx-y=0$ 사이의 거리에서 ${ left(4m-2 right)^{2}} over {m^{2}+1} =2$",
      "$7m^{2}-8m+1=0$ , $left(7m-1 right) left(m-1 right)=0$",
      "$0<m<1$ 이므로 $m= {1} over {7}$"]),

dict(no=15, unit="함수와 그래프", level="하", src="2025-3월 25번", point="무리함수와 역함수의 관계",
 body=["무리함수 $y= sqrt{2x+6} +a$ 의 역함수의 그래프가 두 점 $left(2,`-3 right)$ , $left(b,`5 right)$ 를 지날 때, $a+b$ 의 값을 구하시오. (단, $a$ 는 상수이다.)"],
 choices=None, ans=8,
 sol=["역함수의 그래프가 점 $left(2,`-3 right)$ , $left(b,`5 right)$ 를 지나므로 $y= sqrt{2x+6} +a$ 의 그래프는 점 $left(-3,`2 right)$ , $left(5,`b right)$ 를 지난다.",
      "$2= sqrt{0} +a$ 에서 $a=2$ , $b= sqrt{16} +2=6$",
      "따라서 $a+b=8$"]),

dict(no=16, unit="집합과 명제", level="하", src="2026-3월 22번", point="집합의 연산",
 body=["두 집합",
       "$A= left{x left| x 는~ 12 의~약수 right. right}$ , $B= left{x left| x 는~ 10 ~이하의~소수 right. right}$",
       "에 대하여 집합 $left(A cup B right)- left(A cap B right)$ 의 모든 원소의 합을 구하시오."],
 choices=None, ans=35,
 sol=["$A= left{1,`2,`3,`4,`6,`12 right}$ , $B= left{2,`3,`5,`7 right}$",
      "$left(A cup B right)- left(A cap B right)= left{1,`4,`5,`6,`7,`12 right}$",
      "따라서 모든 원소의 합은 $35$"]),

dict(no=17, unit="도형의 방정식", level="중", src="2026-3월 25번", point="원의 접선과 이차함수의 그래프",
 body=["좌표평면에서 원 $x^{2}+y^{2}=5$ 위의 점 $left(2,`-1 right)$ 에서의 접선이 곡선 $y=x^{2}+ax+a-8$ 에 접할 때, 상수 $a$ 의 값을 구하시오."],
 choices=None, ans=4,
 sol=["원 위의 점 $left(2,`-1 right)$ 에서의 접선은 $2x-y=5$ , 즉 $y=2x-5$",
      "$x^{2}+ax+a-8=2x-5$ 에서 $x^{2}+ left(a-2 right)x+a-3=0$",
      "판별식 $left(a-2 right)^{2}-4 left(a-3 right)= left(a-4 right)^{2}=0$ 이므로 $a=4$"]),

dict(no=18, unit="도형의 방정식", level="중", src="2025-3월 26번", point="외분점과 두 점 사이의 거리의 최대·최소",
 body=["좌표평면 위의 원점 ${rm{O}}$ 와 점 ${rm{A}} left(2,`1 right)$ 에 대하여 선분 ${rm{OA}}$ 를 $2`:`1$ 로 외분하는 점을 ${rm{P}}$ , 점 ${rm{B}} left(6,`-2 right)$ 에 대하여 선분 ${rm{AB}}$ 위의 한 점을 ${rm{Q}}$ 라 하자. ${ bar{rm{PQ}}}^{2}$ 의 최댓값을 $M$ , 최솟값을 $m$ 이라 할 때, $M+m$ 의 값을 구하시오."],
 choices=None, ans=24,
 sol=["${rm{P}}$ 는 선분 ${rm{OA}}$ 를 $2`:`1$ 로 외분하므로 ${rm{P}} left(4,`2 right)$",
      "${ bar{rm{PA}}}^{2} =4+1=5$ , ${ bar{rm{PB}}}^{2} =4+16=20$ 이므로 $M=20$",
      "직선 ${rm{AB}}$ 의 방정식은 $3x+4y-10=0$ 이고 점 ${rm{P}}$ 와의 거리는 ${ left| 12+8-10 right|} over {5} =2$",
      "점 ${rm{P}}$ 에서 직선 ${rm{AB}}$ 에 내린 수선의 발 $left({14} over {5},` {2} over {5} right)$ 는 선분 ${rm{AB}}$ 위에 있으므로 $m=4$",
      "따라서 $M+m=24$"]),

dict(no=19, unit="함수와 그래프", level="상", src="2026-3월 28번", point="합성함수와 집합의 조건",
 body=["집합 $X= left{1,`2,`3,`4,`5,`6,`7,`8,`9 right}$ 에 대하여 함수 $f`:`X rarrow X$ 는",
       "$f left(k right)= left(7^{k} 의~일의~자리의~수 right)$",
       "이다. 다음 조건을 만족시키는 집합 $A$ 에 대하여 $A$ 의 모든 원소의 합의 최댓값을 구하시오."],
 box=["(가) $A subset X$ , $n left(A right) ge 2$",
      "(나) 집합 $A$ 의 임의의 원소 $a$ 에 대하여 $f left(a right) in A$ 이고, $left(f circ f right) left(a right)=3$ 이다.",
      "(다) 집합 $A$ 의 임의의 두 원소 $x$ , $y$ 에 대하여 $x<y$ 이면 $f left(x right) le f left(y right)$ 이다."],
 choices=None, ans=19,
 sol=["$7^{k}$ 의 일의 자리의 수는 $7,`9,`3,`1$ 이 반복되므로",
      "$f left(1 right)=f left(5 right)=f left(9 right)=7$ , $f left(2 right)=f left(6 right)=9$ , $f left(3 right)=f left(7 right)=3$ , $f left(4 right)=f left(8 right)=1$",
      "$left(f circ f right) left(a right)=3$ 이려면 $f left(a right)=3$ 또는 $f left(a right)=7$ 이므로 $A subset left{1,`3,`5,`7,`9 right}$",
      "$A$ 의 원소의 함숫값은 $3$ 또는 $7$ 이고 (나)에서 그 함숫값도 $A$ 에 속하므로 $3 in A$ 또는 $7 in A$ 이다. $7 in A$ 이면 $f left(7 right)=3 in A$ 이므로 어느 경우든 $3 in A$",
      "(다)에서 함숫값이 $7$ 인 원소는 $3$ 보다 커야 하므로 $1 notin A$ 이고, $5 in A$ 또는 $9 in A$ 이면 $7 in A$ 이므로 그 원소는 $7$ 보다 커야 한다. 즉 $5 notin A$",
      "따라서 $A$ 는 $left{3,`7 right}$ 또는 $left{3,`7,`9 right}$ 이고, 원소의 합의 최댓값은 $3+7+9=19$"]),

dict(no=20, unit="집합과 명제", level="최상", src="2026-3월 19번", point="조건을 만족시키는 집합의 추론",
 body=["집합 $X= left{1,`2,`3,`4,`5,`6,`7,`8,`9,`10 right}$ 이 있다. 다음 조건을 만족시키는 집합 $X$ 의 두 부분집합 $A$ , $B$ 에 대하여 집합 $B-A$ 의 모든 원소의 합의 최댓값을 구하시오."],
 box=["(가) $n left(A cap B right)=2$ , $n left(B-A right)=3$",
      "(나) $p in A cap B$ 이면 ${p+1} over {2} in B-A$ 이다.",
      "(다) $q in B-A$ 이면 $q+3 in A$ 이다."],
 choices=None, ans=15,
 sol=["(다)에서 $B-A$ 의 원소 $q$ 는 $q+3 le 10$ , 즉 $q le 7$ 이다.",
      "(나)에서 $A cap B$ 의 원소 $p$ 는 $10$ 이하의 홀수이므로 ${p+1} over {2} le 5$ 이고, 서로 다른 두 원소 $p$ 에 대하여 ${p+1} over {2}$ 는 $B-A$ 의 서로 다른 두 원소이다.",
      "따라서 $B-A$ 는 $5$ 이하의 원소를 $2$ 개 이상 가지므로 원소의 합은 $4+5+7=16$ 이하이다.",
      "합이 $16$ 이면 $B-A= left{4,`5,`7 right}$ 이고 $A cap B= left{7,`9 right}$ 이어야 하는데, $7$ 이 $A cap B$ 와 $B-A$ 에 동시에 속하므로 모순이다.",
      "$A cap B= left{7,`9 right}$ , $B-A= left{4,`5,`6 right}$ 이면 (다)에서 $7,`8,`9 in A$ 이므로 $A= left{7,`8,`9 right}$ , $B= left{4,`5,`6,`7,`9 right}$ 로 모든 조건을 만족시킨다.",
      "따라서 최댓값은 $4+5+6=15$"]),
]
