# -*- coding: utf-8 -*-
# 예비고1 반편성고사 문항 데이터
# 본문 문자열에서 $...$ 는 한글 수식(HWP equation script)
# body: 문단 리스트, box: 조건 상자 문단 리스트(없으면 None), fig: 그림 파일(없으면 None)
# choices: 객관식 5개 수식(단답형은 None), ans: 정답(객관식은 1~5 번호, 단답형은 정수)
# sol: 해설 문단 리스트, src: 변형 원본, unit/level/pts: 단원/난도/배점, point: 평가 요소

PTS = {"하": 3, "중하": 4, "중": 5, "중상": 5, "상": 6, "최상": 6}  # 6점은 상 이상 난도


def points(p):
    """문항 배점: 난도별 배점, 특히 어려운 문항은 pts로 지정(20번 7점)"""
    return p.get("pts") or PTS[p["level"]]

M1 = [
dict(no=1, unit="다항식", level="하", src="2025-3월 7번", point="곱셈 공식의 변형",
 body=["$a-b=3$, $a^{3}-b^{3}=63$ 일 때, $ab$ 의 값은?"],
 choices=["1", "2", "3", "4", "5"], ans=4,
 sol=["$a^{3}-b^{3}= left(a-b right)^{3}+3ab left(a-b right)$ 이므로",
      "$63=27+9ab$ , $9ab=36$",
      "따라서 $ab=4$"]),

dict(no=2, unit="행렬", level="하", src="2026-3월 6번", point="행렬의 성분과 덧셈·실수배",
 body=["이차정사각행렬 $A$ , $B$ 의 $left(i,`j right)$ 성분을 각각 $a_{ij}$ , $b_{ij}$ 라 할 때,",
       "$a_{ij}=2i-j$ , $b_{ij}=ij~ left(i=1,`2,~j=1,`2 right)$",
       "이다. 행렬 $A+2B$ 의 모든 성분의 합은?"],
 choices=["22", "24", "26", "28", "30"], ans=2,
 sol=["$A= left( rpile{ 1 && 0 # 3 && 2 } right)$ , $B= left( rpile{ 1 && 2 # 2 && 4 } right)$ 이므로",
      "$A+2B= left( rpile{ 3 && 4 # 7 && 10 } right)$",
      "따라서 모든 성분의 합은 $3+4+7+10=24$"]),

dict(no=3, unit="방정식과 부등식", level="하", src="2026-3월 7번", point="인수정리를 이용한 삼차방정식의 풀이",
 body=["삼차방정식 $x^{3}-4x^{2}+x+6=0$ 의 모든 양의 실근의 합은?"],
 choices=["3", "4", "5", "6", "7"], ans=3,
 sol=["$x=-1$ 을 대입하면 $-1-4-1+6=0$ 이므로 $x+1$ 은 인수이다.",
      "$x^{3}-4x^{2}+x+6= left(x+1 right) left(x^{2}-5x+6 right)= left(x+1 right) left(x-2 right) left(x-3 right)$",
      "양의 실근은 $2$ , $3$ 이므로 그 합은 $5$"]),

dict(no=4, unit="방정식과 부등식", level="중하", src="2025-3월 8번", point="연립이차부등식의 해",
 body=["연립부등식",
       "$cases{ x^{2}-2x-8 ge 0 # x^{2}-36 < 0}$",
       "을 만족시키는 모든 정수 $x$ 의 값의 합은?"],
 choices=["-9", "-8", "-7", "-6", "-5"], ans=5,
 sol=["$x^{2}-2x-8 ge 0$ 에서 $left(x+2 right) left(x-4 right) ge 0$ , 즉 $x le -2$ 또는 $x ge 4$",
      "$x^{2}-36<0$ 에서 $-6<x<6$",
      "공통 범위는 $-6<x le -2$ 또는 $4 le x<6$ 이므로 정수 $x$ 는 $-5,`-4,`-3,`-2,`4,`5$",
      "그 합은 $-14+9=-5$"]),

dict(no=5, unit="다항식", level="중하", src="2026-3월 9번", point="나머지정리와 나머지의 결정",
 body=["다항식 $P left(x right)$ 에 대하여 $P left(x+1 right)$ 을 $x$ 로 나눈 나머지는 $5$ 이고, $P left(x-2 right)$ 를 $x+1$ 로 나눈 나머지는 $-3$ 이다. 다항식 $P left(x right)$ 를 $x^{2}+2x-3$ 으로 나눈 나머지를 $R left(x right)$ 라 할 때, $R left(2 right)$ 의 값은?"],
 choices=["7", "9", "11", "13", "15"], ans=1,
 sol=["나머지정리에 의하여 $P left(1 right)=5$ , $P left(-3 right)=-3$",
      "$x^{2}+2x-3= left(x-1 right) left(x+3 right)$ 이므로 $R left(x right)=ax+b$ 라 하면",
      "$P left(x right)= left(x-1 right) left(x+3 right)Q left(x right)+ax+b$",
      "$a+b=5$ , $-3a+b=-3$ 에서 $a=2$ , $b=3$",
      "따라서 $R left(2 right)=2 TIMES 2+3=7$"]),

dict(no=6, unit="방정식과 부등식", level="중하", src="2025-10월 8번", point="일차식을 대입하는 연립이차방정식",
 body=["연립방정식",
       "$cases{ x+y=2 # x^{2}-3x+2y=10 }$",
       "의 해를 $x= alpha$ , $y= beta$ 라 할 때, $alpha^{2}+ beta^{2}$ 의 최댓값은?"],
 choices=["48", "50", "52", "54", "56"], ans=3,
 sol=["$x+y=2$ 에서 $y=2-x$ 를 $x^{2}-3x+2y=10$ 에 대입하면 $x^{2}-5x-6=0$",
      "$left(x+1 right) left(x-6 right)=0$ 에서 $x=-1$ 또는 $x=6$",
      "해는 $x=-1$ , $y=3$ 또는 $x=6$ , $y=-4$ 이므로 $alpha^{2}+ beta^{2}$ 의 값은 $10$ 또는 $52$",
      "따라서 최댓값은 $52$"]),

dict(no=7, unit="방정식과 부등식", level="중상", src="2024-3월 15번", point="켤레복소수의 성질과 복소수가 0이 될 조건",
 body=["다음 조건을 만족시키는 복소수 $z$ 가 존재하도록 하는 모든 실수 $k$ 의 값의 곱은? (단, ${ bar{z}}$ 는 $z$ 의 켤레복소수이다.)"],
 box=["(가) ${ bar{z}} =-z$",
      "(나) $z^{2}+ left(k^{2}-2k-8 right)z+k^{2}+k-6=0$"],
 choices=["-36", "-32", "-28", "-24", "-20"], ans=4,
 sol=["(가)에서 $z=bi$ ( $b$ 는 실수)로 놓을 수 있다.",
      "(나)에 대입하면 $-b^{2}+k^{2}+k-6+ left(k^{2}-2k-8 right)bi=0$ 이므로 $b^{2}=k^{2}+k-6$ , $left(k^{2}-2k-8 right)b=0$",
      "(i) $b=0$ , 즉 $z=0$ 일 때: $k^{2}+k-6=0$ 에서 $k=2$ 또는 $k=-3$",
      "(ii) $b ne 0$ 일 때: $k^{2}-2k-8=0$ 에서 $k=4$ 또는 $k=-2$ 이고, $b^{2}=k^{2}+k-6>0$ 이어야 하므로 $k=4$ ( $b^{2}=14$ )",
      "따라서 모든 $k$ 의 값의 곱은 $2 TIMES left(-3 right) TIMES 4=-24$"]),

dict(no=8, unit="경우의 수", level="중상", src="2025-10월 16번", point="이웃하지 않게 나열하는 경우의 수",
 body=["$1$ 학년 학생 $4$ 명, $2$ 학년 학생 $2$ 명, $3$ 학년 학생 $1$ 명이 있다. 이 $7$ 명의 학생 중에서 $5$ 명의 학생을 선택하고 이 $5$ 명의 학생이 모두 한 번씩 발표하도록 순서를 정하려고 할 때, $1$ 학년 학생끼리는 연속해서 발표하지 않도록 순서를 정하는 경우의 수는? (단, 발표는 한 명씩 한다.)"],
 choices=["552", "576", "600", "624", "648"], ans=2,
 sol=["$1$ 학년이 아닌 학생은 $3$ 명이므로 선택한 $5$ 명 중 $1$ 학년 학생은 $2$ 명 이상이다.",
      "(i) $1$ 학년 학생이 $2$ 명일 때: $1$ 학년 학생을 고르는 ${}_{4} rm C _{2} =6$ 가지, 나머지 $3$ 명을 일렬로 세우는 $3!=6$ 가지, 그 사이와 양 끝의 $4$ 곳 중 $2$ 곳에 $1$ 학년 학생을 세우는 ${}_{4} rm P _{2} =12$ 가지이므로 $6 TIMES 6 TIMES 12=432$",
      "(ii) $1$ 학년 학생이 $3$ 명일 때: 학생을 고르는 ${}_{4} rm C _{3} TIMES {}_{3} rm C _{2} =12$ 가지, 다른 학년 $2$ 명을 세우는 $2!=2$ 가지, $3$ 곳에 $1$ 학년 학생을 세우는 $3!=6$ 가지이므로 $12 TIMES 2 TIMES 6=144$",
      "(iii) $1$ 학년 학생이 $4$ 명이면 다른 학년 학생이 $1$ 명뿐이므로 $1$ 학년 학생끼리 연속하지 않게 할 수 없다.",
      "따라서 구하는 경우의 수는 $432+144=576$"]),

dict(no=9, unit="방정식과 부등식", level="중상", src="자체 출제", point="복소수의 거듭제곱의 주기성",
 body=["복소수 $z={1-i} over {1+i}$ 에 대하여 $z+2z^{2}+3z^{3}+ CDOTS +20z^{20}=a+bi$ 일 때, 두 실수 $a$ , $b$ 에 대하여 $a+b$ 의 값은? (단, $i= sqrt{-1}$ )"],
 choices=["4", "8", "12", "16", "20"], ans=5,
 sol=["$z={ left(1-i right)^{2}} over { left(1+i right) left(1-i right)} ={-2i} over {2} =-i$",
      "$z^{2}=-1$ , $z^{3}=i$ , $z^{4}=1$ 이므로 $z^{n+4}=z^{n}$ 이다.",
      "연속한 네 항 $left(4m+1 right)z^{4m+1}+ left(4m+2 right)z^{4m+2}+ left(4m+3 right)z^{4m+3}+ left(4m+4 right)z^{4m+4}$ 의 합은 $- left(4m+1 right)i- left(4m+2 right)+ left(4m+3 right)i+ left(4m+4 right)=2+2i$",
      "$m=0,`1,`2,`3,`4$ 의 $5$ 묶음이므로 $z+2z^{2}+ CDOTS +20z^{20}=5 left(2+2i right)=10+10i$",
      "따라서 $a=10$ , $b=10$ 이고 $a+b=20$"]),

dict(no=10, unit="행렬", level="상", src="2025-10월 15번", point="행렬의 곱셈과 영행렬 조건의 추론",
 body=["세 이차정사각행렬 $A= left( rpile{ 0 && 12 # 0 && 0 } right)$ , $B$ , $C$ 가 다음 조건을 만족시킨다."],
 box=["(가) $AB=CA=O$",
      "(나) 행렬 $B$ 의 모든 성분의 합이 $4$ 이고, 행렬 $C$ 의 $left(1,`2 right)$ 성분과 $left(2,`2 right)$ 성분이 같다."],
 body2=["$BC=A$ 일 때, 행렬 $C$ 의 모든 성분의 합은? (단, $O$ 는 영행렬이다.)"],
 choices=["6", "7", "8", "9", "10"], ans=1,
 sol=["$B= left( rpile{ p && q # r && s } right)$ , $C= left( rpile{ u && v # w && z } right)$ 라 하자.",
      "$AB= left( rpile{ 12r && 12s # 0 && 0 } right)=O$ 에서 $r=s=0$ , $CA= left( rpile{ 0 && 12u # 0 && 12w } right)=O$ 에서 $u=w=0$",
      "$BC= left( rpile{ 0 && pv+qz # 0 && 0 } right)=A$ 에서 $pv+qz=12$",
      "(나)에서 $p+q=4$ , $v=z$ 이므로 $v left(p+q right)=4v=12$ , $v=3$",
      "따라서 $C= left( rpile{ 0 && 3 # 0 && 3 } right)$ 이고 모든 성분의 합은 $6$"]),

dict(no=11, unit="경우의 수", level="상", src="2025-3월 18번", point="조건을 만족시키는 배열의 경우의 수",
 body=["어느 숙소에는 그림과 같이 객실 번호가 적힌 $10$ 개의 객실이 있다."],
 fig="room.png",
 body2=["관광객 ${rm{A}}$ , ${rm{B}}$ , ${rm{C}}$ 를 포함한 $5$ 명의 관광객이 다음 규칙에 따라 $10$ 개의 객실 중에서 각자 서로 다른 한 객실에 숙박하는 경우의 수는?"],
 box=["(가) $5$ 명의 관광객 중 어느 관광객도 객실 번호가 $102$ , $204$ 인 객실에는 숙박하지 않는다.",
      "(나) ${rm{A}}$ 와 ${rm{B}}$ 가 숙박하는 객실 번호의 차는 $1$ 이다.",
      "(다) ${rm{A}}$ 와 ${rm{C}}$ 가 숙박하는 객실 번호의 차는 $4$ 보다 크고 $100$ 이 아니다."],
 choices=["520", "560", "600", "640", "680"], ans=2,
 sol=["숙박 가능한 객실은 $1$ 층 $101,`103,`104,`105$ , $2$ 층 $201,`202,`203,`205$ 이다.",
      "(나)에서 ${rm{A}}$ , ${rm{B}}$ 는 같은 층의 번호가 연속인 두 객실이므로 $left{103,`104 right}$ , $left{104,`105 right}$ , $left{201,`202 right}$ , $left{202,`203 right}$ 중 하나이다.",
      "(다)에서 같은 층의 두 객실 번호의 차는 $4$ 이하이므로 ${rm{C}}$ 는 ${rm{A}}$ 와 다른 층에 있고, ${rm{A}}$ 의 바로 위 또는 아래 객실은 제외한다.",
      "${rm{A}}$ 의 객실이 $103$ , $104$ , $104$ , $105$ , $201$ , $202$ , $202$ , $203$ 인 $8$ 가지 경우에 ${rm{C}}$ 의 객실의 수는 각각 $3,`4,`4,`3,`3,`4,`4,`3$ 이므로 합은 $28$ ( $104$ , $202$ 는 바로 위·아래 객실이 숙박 금지 객실이다.)",
      "남은 $2$ 명은 남은 $5$ 개의 객실 중 $2$ 개에 숙박하므로 ${}_{5} rm P _{2} =20$",
      "따라서 구하는 경우의 수는 $28 TIMES 20=560$"]),

dict(no=12, unit="방정식과 부등식", level="상", src="2025-3월 17번", point="이차방정식의 근과 서로 다른 실근의 개수",
 body=["이차함수 $f left(x right)=x^{2}-3x-4$ 가 있다. 실수 $k$ 에 대하여 $x$ 에 대한 방정식 $f left(x right)f left(x-k right)=0$ 의 서로 다른 실근의 개수를 $g left(k right)$ 라 하자. $g left(k-6 right)+g left(k+4 right)=6$ 이 되도록 하는 모든 $k$ 의 값의 합은?"],
 choices=["1", "2", "3", "4", "5"], ans=3,
 sol=["$f left(x right)= left(x+1 right) left(x-4 right)$ 이므로 $f left(x right)=0$ 의 근은 $-1$ , $4$ 이고, $f left(x-k right)=0$ 의 근은 $k-1$ , $k+4$ 이다.",
      "따라서 $g left(k right)=2~ left(k=0 right)$ , $g left(k right)=3~ left(k=5~또는~k=-5 right)$ , 그 외에는 $g left(k right)=4$",
      "합이 $6$ 이 되는 경우는 $left(2,`4 right)$ , $left(4,`2 right)$ , $left(3,`3 right)$ 이다.",
      "(i) $g left(k-6 right)=2$ : $k=6$ 이고 $g left(10 right)=4$ 이므로 성립",
      "(ii) $g left(k+4 right)=2$ : $k=-4$ 이고 $g left(-10 right)=4$ 이므로 성립",
      "(iii) $k-6$ 과 $k+4$ 가 모두 $5$ 또는 $-5$ : 두 수의 차가 $10$ 이므로 $k-6=-5$ , $k+4=5$ , 즉 $k=1$",
      "따라서 모든 $k$ 의 값의 합은 $6+ left(-4 right)+1=3$"]),

dict(no=13, unit="다항식", level="최상", src="2026-3월 20번", point="다항식의 나눗셈과 인수의 추론",
 body=["최고차항의 계수가 $1$ 인 서로 다른 세 이차다항식 $f left(x right)$ , $g left(x right)$ , $h left(x right)$ 가 다음 조건을 만족시킨다."],
 box=["(가) 다항식 $f left(x right)g left(x right)$ 는 다항식 $left(x+1 right)h left(x right)$ 로 나누어떨어진다.",
      "(나) 다항식 $g left(x right)h left(x right)$ 는 다항식 $left(x-3 right)f left(x right)$ 로 나누어떨어진다."],
 body2=["$f left(1 right)+g left(1 right)=-12$ 일 때, $h left(0 right)$ 의 값은?"],
 choices=["9", "11", "13", "15", "17"], ans=4,
 sol=["차수를 비교하면 최고차항의 계수가 $1$ 인 일차식 $P left(x right)$ , $Q left(x right)$ 에 대하여",
      "$f left(x right)g left(x right)= left(x+1 right)h left(x right)P left(x right)$ , $g left(x right)h left(x right)= left(x-3 right)f left(x right)Q left(x right)$",
      "두 식을 변끼리 곱하면 $left{g left(x right) right}^{2}= left(x+1 right) left(x-3 right)P left(x right)Q left(x right)$",
      "좌변의 각 근은 중근이므로 $left{P,`Q right}= left{x+1,`x-3 right}$ 이고 $g left(x right)= left(x+1 right) left(x-3 right)$",
      "$P left(x right)=x-3$ 이면 첫 식에서 $f left(x right)=h left(x right)$ 가 되어 모순이므로 $P left(x right)=x+1$ , 즉 $f left(x right) left(x-3 right)=h left(x right) left(x+1 right)$",
      "따라서 $f left(x right)= left(x+1 right) left(x-u right)$ , $h left(x right)= left(x-3 right) left(x-u right)$ 꼴이다.",
      "$f left(1 right)+g left(1 right)=2 left(1-u right)-4=-12$ 에서 $u=5$",
      "$h left(0 right)= left(-3 right) TIMES left(-5 right)=15$"]),

dict(no=14, unit="방정식과 부등식", level="최상", src="2026-3월 18번", point="이차함수의 그래프와 방정식의 실근의 개수",
 body=["최고차항의 계수가 $1$ 인 이차함수 $f left(x right)$ 가 있다. $x$ 에 대한 방정식",
       "$f left(x right) TIMES left{f left(x right)+2f left(t right) right}=0$",
       "의 서로 다른 실근의 개수가 $3$ 이 되도록 하는 모든 실수 $t$ 의 값이 $-1$ , $5$ 일 때, $f left(8 right)$ 의 값은?"],
 choices=["22", "24", "26", "28", "30"], ans=5,
 sol=["$f left(x right)= left(x-p right)^{2}+q$ 라 하자. 주어진 방정식은 $f left(x right)=0$ 또는 $f left(x right)=-2f left(t right)$ 이다.",
      "$q>0$ 이면 $f left(x right)=0$ 은 실근이 없으므로 실근은 $2$ 개 이하이다. $q=0$ 이면 $f left(x right)=0$ 의 근은 $p$ 하나이고, $left(x-p right)^{2}=-2 left(t-p right)^{2}$ 은 $x=p$ 외의 근이 없으므로 실근은 $1$ 개이다. 따라서 $q<0$",
      "$q<0$ 이면 $f left(x right)=0$ 은 서로 다른 두 실근을 가진다. $f left(t right)=0$ 이면 두 방정식이 같아 실근은 $2$ 개이므로, 실근이 $3$ 개가 되려면 $f left(x right)=-2f left(t right)$ 가 중근을 가져야 한다.",
      "$left(x-p right)^{2}=-q-2f left(t right)$ 가 중근을 가지려면 $-q-2 left{ left(t-p right)^{2}+q right}=0$ , 즉 $left(t-p right)^{2}=-{3} over {2}q$",
      "이를 만족시키는 $t$ 는 $p PLUSMINUS sqrt{-{3} over {2}q}$ 이므로 $p={-1+5} over {2}=2$ , $-{3} over {2}q=9$ 에서 $q=-6$",
      "$f left(x right)= left(x-2 right)^{2}-6$ 이므로 $f left(8 right)=36-6=30$"]),

dict(no=15, unit="방정식과 부등식", level="중상", src="2025-10월 27번", point="이차방정식의 근의 성질과 근과 계수의 관계",
 body=["상수 $k$ 에 대하여 $x$ 에 대한 이차방정식 $x^{2}+kx-{1} over {2}k^{2}+4k=0$ 이 서로 다른 두 실근 $alpha$ , $beta$ 를 갖는다. $alpha^{2}-k beta =14$ 일 때, $alpha^{2}+ beta^{2}$ 의 값을 구하시오."],
 choices=None, ans=24,
 sol=["$alpha$ 는 이 방정식의 근이므로 $alpha^{2}=-k alpha +{1} over {2}k^{2}-4k$",
      "$alpha + beta =-k$ 이므로 $alpha^{2}-k beta =-k left( alpha + beta right)+{1} over {2}k^{2}-4k={3} over {2}k^{2}-4k=14$",
      "$3k^{2}-8k-28=0$ , $left(3k-14 right) left(k+2 right)=0$ 에서 $k={14} over {3}$ 또는 $k=-2$",
      "서로 다른 두 실근을 가지려면 판별식 $D=k^{2}-4 left(-{1} over {2}k^{2}+4k right)=3k^{2}-16k>0$ , 즉 $k<0$ 또는 $k>{16} over {3}$ 이므로 $k=-2$",
      "$alpha + beta =2$ , $alpha beta =-2-8=-10$ 이므로 $alpha^{2}+ beta^{2}=4+20=24$"]),

dict(no=16, unit="경우의 수", level="중상", src="2026-9월 17번", point="조건을 만족시키는 일렬 배열의 경우의 수",
 body=["숫자 $1$ , $2$ , $3$ , $4$ , $5$ , $6$ , $7$ 이 하나씩 적혀 있는 $7$ 장의 카드가 있다. 이 $7$ 장의 카드를 모두 한 번씩 사용하여 일렬로 나열할 때, 다음 조건을 만족시키는 경우의 수를 구하시오."],
 box=["(가) 양 끝에 놓인 카드에 적힌 수는 모두 홀수이다.",
      "(나) 숫자 $4$ 가 적힌 카드의 바로 양옆에 놓인 카드에 적힌 두 수의 합은 홀수이다."],
 choices=None, ans=864,
 sol=["양 끝에 홀수 카드를 놓는 경우의 수는 ${}_{4} rm P _{2} =12$ 이고, 나머지 $5$ 장(홀수 $2$ 장과 $2$ , $4$ , $6$ )을 가운데 $5$ 자리에 놓는 경우의 수는 $5!=120$ 이다.",
      "이 중 $4$ 의 양옆이 모두 짝수이거나 모두 홀수인 경우를 뺀다.",
      "(i) 양옆이 $2$ , $6$ 인 경우: $2$ , $4$ , $6$ 을 한 묶음(순서 $2$ 가지)으로 보면 묶음의 위치 $3$ 가지, 홀수 $2$ 장의 배열 $2$ 가지이므로 $2 TIMES 3 TIMES 2=12$",
      "(ii) 양옆이 모두 홀수인 경우: $4$ 가 가운데 $5$ 자리의 맨 앞 또는 맨 뒤이면 한쪽은 끝의 홀수 카드이므로 다른 쪽에 홀수 $2$ 장 중 하나, 나머지 $3$ 장의 배열 $3!$ 에서 $2 TIMES 2 TIMES 6=24$ , 그 외의 $3$ 자리이면 양옆에 홀수 $2$ 장을 놓는 $2$ 가지, 나머지 $2$ 장의 배열 $2$ 가지에서 $3 TIMES 2 TIMES 2=12$",
      "따라서 구하는 경우의 수는 $12 TIMES left(120-12-24-12 right)=12 TIMES 72=864$"]),

dict(no=17, unit="다항식", level="중상", src="2025-10월 18번", point="인수정리와 완전제곱식을 이용한 인수분해",
 body=["$x$ 에 대한 다항식 $x^{3}+ left(2a+1 right)x^{2}+ left(3a+2 right)x+a+2$ 가 $left(x+b right) left(x+c right)^{2}$ 으로 인수분해되도록 하는 세 실수 $a$ , $b$ , $c$ 에 대하여 $a+b+c$ 의 최댓값을 $M$ , 최솟값을 $m$ 이라 할 때, $M+m$ 의 값을 구하시오."],
 choices=None, ans=8,
 sol=["$x=-1$ 을 대입하면 $-1+2a+1-3a-2+a+2=0$ 이므로 주어진 다항식은 $x+1$ 을 인수로 갖는다.",
      "$x^{3}+ left(2a+1 right)x^{2}+ left(3a+2 right)x+a+2= left(x+1 right) left(x^{2}+2ax+a+2 right)$",
      "(i) $x^{2}+2ax+a+2$ 가 완전제곱식인 경우: $a^{2}=a+2$ 에서 $a=2$ 또는 $a=-1$",
      "$a=2$ 이면 $left(x+1 right) left(x+2 right)^{2}$ 이므로 $b=1$ , $c=2$ , $a+b+c=5$",
      "$a=-1$ 이면 $left(x+1 right) left(x-1 right)^{2}$ 이므로 $b=1$ , $c=-1$ , $a+b+c=-1$",
      "(ii) $x^{2}+2ax+a+2$ 가 $x+1$ 을 인수로 갖는 경우: $1-2a+a+2=0$ 에서 $a=3$ 이고 $left(x+1 right)^{2} left(x+5 right)$ 이므로 $b=5$ , $c=1$ , $a+b+c=9$",
      "따라서 $M=9$ , $m=-1$ 이므로 $M+m=8$"]),

dict(no=18, unit="행렬", level="상", src="2026-3월 29번", point="행렬의 곱셈과 성분 조건의 추론",
 body=["영행렬이 아닌 두 행렬 $A= left( rpile{ a_{11} && a_{12} # a_{21} && a_{22} } right)$ , $B= left( rpile{ b_{11} && b_{12} # b_{21} && b_{22} } right)$ 는 $A^{2}=B$ 이고, 각 행렬의 성분은 다음 조건을 만족시킨다."],
 box=["(가) 모든 $i$ , $j~ left(i=1,`2,~j=1,`2 right)$ 에 대하여 $a_{ij} TIMES b_{ij}=0$ 이다.",
      "(나) 모든 $i$ , $j~ left(i=1,`2,~j=1,`2 right)$ 에 대하여 $a_{ij}+b_{ij} ne 0$ 이다."],
 body2=["행렬 $A+B$ 의 모든 성분의 합이 $2$ , 곱이 $-1$ 일 때, $a_{12}^{3}+a_{21}^{3}$ 의 값을 구하시오. (단, $A^{2}=AA$ 이고, 행렬 $A$ 의 모든 성분은 실수이다.)"],
 choices=None, ans=76,
 sol=["$A= left( rpile{ a && b # c && d } right)$ 라 하면 $A^{2}= left( rpile{ a^{2}+bc && b left(a+d right) # c left(a+d right) && d^{2}+bc } right)$",
      "$b=0$ 이면 $b_{12}=0$ 이 되어 (나)에 모순이므로 $b ne 0$ , 같은 방법으로 $c ne 0$ . (가)에서 $b left(a+d right)=0$ 이므로 $a+d=0$",
      "이때 $B= left( rpile{ a^{2}+bc && 0 # 0 && a^{2}+bc } right)$ 이고, $a ne 0$ 이면 (가)에서 $a^{2}+bc=0$ , 즉 $B=O$ 이므로 모순. 따라서 $a=d=0$",
      "$A+B= left( rpile{ bc && b # c && bc } right)$ 이므로 성분의 곱 $left(bc right)^{3}=-1$ 에서 $bc=-1$",
      "성분의 합 $2bc+b+c=2$ 에서 $b+c=4$",
      "$a_{12}^{3}+a_{21}^{3}=b^{3}+c^{3}= left(b+c right)^{3}-3bc left(b+c right)=64+12=76$"]),

dict(no=19, unit="방정식과 부등식", level="최상", src="2025-10월 17번", point="제한된 범위에서 이차함수의 최대·최소",
 body=["양수 $a$ 와 실수 $k$ 에 대하여 $0 le x le a$ 에서 이차함수 $f left(x right)=x^{2}-2kx+k^{2}+1$ 의 최댓값이 $10$ 이고 최솟값이 $1$ 이다. $a+k$ 의 최댓값을 $M$ , 최솟값을 $m$ 이라 할 때, $M TIMES m$ 의 값을 구하시오."],
 choices=None, ans=27,
 sol=["$f left(x right)= left(x-k right)^{2}+1 ge 1$ 이므로 최솟값이 $1$ 이려면 꼭짓점의 $x$ 좌표 $k$ 가 $0 le k le a$ 이어야 한다.",
      "이때 최댓값은 $f left(0 right)=k^{2}+1$ , $f left(a right)= left(a-k right)^{2}+1$ 중 크거나 같은 값이므로 $k$ 와 $a-k$ 중 크거나 같은 값이 $3$ 이다.",
      "(i) $k ge a-k$ 이면 $k=3$ 이고 $3 le a le 6$ 이므로 $6 le a+k le 9$",
      "(ii) $k le a-k$ 이면 $a-k=3$ 이고 $0 le k le 3$ 이므로 $a+k=2k+3$ 에서 $3 le a+k le 9$",
      "따라서 $M=9$ , $m=3$ 이고 $M TIMES m=27$"]),

dict(no=20, unit="다항식", level="최상", pts=7, src="2024-3월 29번", point="다항식의 인수와 나머지, 판별식의 활용",
 body=["다항식 $f left(x right)=x^{4}+ left(a-2 right)x^{3}+bx^{2}+ax+10$ 과 최고차항의 계수가 $1$ 이고 계수와 상수항이 모두 실수인 두 다항식 $g left(x right)$ , $h left(x right)$ 가 다음 조건을 만족시킨다."],
 box=["(가) 방정식 $f left(x right)=0$ 은 실근을 갖지 않는다.",
      "(나) 다항식 $f left(x right)$ 는 두 다항식 $g left(x right)$ , $h left(x right)$ 를 인수로 갖고, $h left(x right)$ 를 $g left(x right)$ 로 나눈 나머지는 $-2x-3$ 이다."],
 body2=["$a^{2}+b^{2}$ 의 값을 구하시오. (단, $a$ , $b$ 는 상수이다.)"],
 choices=None, ans=65,
 sol=["(가)에서 $f left(x right)$ 는 일차식을 인수로 갖지 않으므로 $g left(x right)$ , $h left(x right)$ 는 각각 이차식이거나 $f left(x right)$ 이다.",
      "$h left(x right)=f left(x right)$ 이면 나머지가 $0$ 이고, $g left(x right)=f left(x right)$ 이면 나머지가 이차식인 $h left(x right)$ 이므로 모두 모순이다. 따라서 $g left(x right)$ , $h left(x right)$ 는 서로 다른 이차식이다.",
      "$h left(x right)=g left(x right)-2x-3$ 이고 $f left(x right)=g left(x right)h left(x right)$ 이므로 $g left(x right)=x^{2}+px+q$ 라 하면",
      "$f left(x right)= left(x^{2}+px+q right) left{x^{2}+ left(p-2 right)x+q-3 right}$",
      "상수항에서 $q left(q-3 right)=10$ 이므로 $q=5$ 또는 $q=-2$ 이고, $g left(x right)=0$ 이 실근을 갖지 않으려면 $p^{2}-4q<0$ 이므로 $q>0$ , 즉 $q=5$",
      "$x^{3}$ 의 계수에서 $2p-2=a-2$ , $x$ 의 계수에서 $2p+5 left(p-2 right)=a$ 이므로 $2p=7p-10$ , $p=2$ , $a=4$",
      "이때 $g left(x right)=x^{2}+2x+5$ , $h left(x right)=x^{2}+2$ 는 모두 실근을 갖지 않으므로 조건을 만족시키고, $x^{2}$ 의 계수에서 $b=5+2+2 TIMES 0=7$",
      "따라서 $a^{2}+b^{2}=16+49=65$"]),
]

M2 = [
dict(no=1, unit="도형의 방정식", level="하", src="2026-3월 5번", point="수직인 두 직선의 기울기",
 body=["두 점 $left(1,`2 right)$ , $left(3,`8 right)$ 을 지나는 직선에 수직이고 점 $left(3,`1 right)$ 을 지나는 직선의 $y$ 절편은?"],
 choices=["1", "2", "3", "4", "5"], ans=2,
 sol=["두 점을 지나는 직선의 기울기는 ${8-2} over {3-1} =3$ 이므로 수직인 직선의 기울기는 $-{1} over {3}$",
      "점 $left(3,`1 right)$ 을 지나므로 $y-1=-{1} over {3} left(x-3 right)$ , 즉 $y=-{1} over {3}x+2$",
      "따라서 $y$ 절편은 $2$"]),

dict(no=2, unit="함수와 그래프", level="하", src="2026-3월 4번", point="대응 관계와 합성함수·역함수의 값",
 body=["그림은 함수 $f`:`X rarrow X$ 를 나타낸 것이다."],
 fig="mapping.png",
 body2=["$left(f circ f right) left(1 right)+f^{-1} left(5 right)$ 의 값은?"],
 choices=["2", "3", "4", "5", "6"], ans=4,
 sol=["그림에서 $f left(1 right)=4$ , $f left(4 right)=2$ 이므로 $left(f circ f right) left(1 right)=f left(4 right)=2$",
      "$f left(3 right)=5$ 이므로 $f^{-1} left(5 right)=3$",
      "따라서 구하는 값은 $2+3=5$"]),

dict(no=3, unit="함수와 그래프", level="하", src="2025-3월 5번", point="역함수의 성질",
 body=["일차함수 $f left(x right)=ax-3$ 의 역함수 $f^{-1} left(x right)$ 에 대하여 $f^{-1} left(5 right)=2$ 일 때, $f^{-1} left(13 right)$ 의 값은? (단, $a$ 는 상수이다.)"],
 choices=["4", "5", "6", "7", "8"], ans=1,
 sol=["$f^{-1} left(5 right)=2$ 이므로 $f left(2 right)=2a-3=5$ , $a=4$",
      "$f^{-1} left(13 right)=k$ 라 하면 $f left(k right)=4k-3=13$ 이므로 $k=4$"]),

dict(no=4, unit="도형의 방정식", level="중하", src="2026-3월 23번", point="삼각형의 무게중심",
 body=["좌표평면 위의 세 점 ${rm{A}} left(1,`4 right)$ , ${rm{B}} left(a,`-2 right)$ , ${rm{C}} left(5,`b right)$ 에 대하여 삼각형 ${rm{ABC}}$ 의 무게중심의 좌표가 $left(3,`2 right)$ 일 때, $a+b$ 의 값은?"],
 choices=["5", "6", "7", "8", "9"], ans=3,
 sol=["${1+a+5} over {3} =3$ 에서 $a=3$ , ${4+ left(-2 right)+b} over {3} =2$ 에서 $b=4$",
      "따라서 $a+b=7$"]),

dict(no=5, unit="도형의 방정식", level="중하", src="2025-3월 9번", point="도형의 평행이동과 대칭이동",
 body=["직선 $y=ax+3$ 을 $x$ 축의 방향으로 $2$ 만큼, $y$ 축의 방향으로 $-1$ 만큼 평행이동한 후, $x$ 축에 대하여 대칭이동한 직선이 원 $x^{2}+y^{2}+2x-8y+8=0$ 의 넓이를 이등분할 때, 상수 $a$ 의 값은?"],
 choices=["-2", "-1", "0", "1", "2"], ans=5,
 sol=["평행이동한 직선은 $y+1=a left(x-2 right)+3$ , 즉 $y=a left(x-2 right)+2$",
      "$x$ 축에 대하여 대칭이동하면 $-y=a left(x-2 right)+2$ , 즉 $y=-a left(x-2 right)-2$",
      "원 $left(x+1 right)^{2}+ left(y-4 right)^{2}=9$ 의 넓이를 이등분하려면 중심 $left(-1,`4 right)$ 를 지나야 하므로",
      "$4=-a left(-3 right)-2$ , $3a=6$ , $a=2$"]),

dict(no=6, unit="집합과 명제", level="중하", src="2026-3월 11번", point="충분조건과 진리집합의 포함 관계",
 body=["실수 $x$ 에 대한 두 조건",
       "$p`:` left| x-a right| >3$ ,",
       "$q`:`x^{2}-6x+8 le 0$",
       "이 있다. $q$ 가 $~ sim p$ 이기 위한 충분조건이 되도록 하는 모든 정수 $a$ 의 값의 합은?"],
 choices=["12", "15", "18", "21", "24"], ans=2,
 sol=["$q$ 의 진리집합은 $Q= left{x left| 2 le x le 4 right. right}$",
      "$sim p`:` left| x-a right| le 3$ 의 진리집합은 $left{x left| a-3 le x le a+3 right. right}$",
      "$Q$ 가 이 집합에 포함되어야 하므로 $a-3 le 2$ , $a+3 ge 4$ , 즉 $1 le a le 5$",
      "정수 $a$ 는 $1,`2,`3,`4,`5$ 이므로 합은 $15$"]),

dict(no=7, unit="집합과 명제", level="중상", src="2025-3월 15번", point="필요조건과 진리집합의 포함 관계",
 body=["실수 $x$ 에 대한 두 조건",
       "$p`:` left(x-2a right) left(x+a right)>0$ ,",
       "$q`:` left| x-1 right| le 5$",
       "가 있다. $q$ 가 $~ sim p$ 이기 위한 필요조건이 되도록 하는 실수 $a$ 의 최댓값을 $M$ , 최솟값을 $m$ 이라 할 때, $Mm$ 의 값은?"],
 choices=["-10", "-9", "-8", "-7", "-6"], ans=5,
 sol=["$q$ 의 진리집합은 $Q= left{x left| -4 le x le 6 right. right}$ 이고, $sim p`:` left(x-2a right) left(x+a right) le 0$ 의 진리집합을 $P^{C}$ 라 하면 $P^{C} subset Q$ 이어야 한다.",
      "(i) $a>0$ 일 때 $P^{C}= left{x left| -a le x le 2a right. right}$ 이므로 $-a ge -4$ , $2a le 6$ 에서 $0<a le 3$",
      "(ii) $a=0$ 일 때 $P^{C}= left{0 right}$ 이므로 성립",
      "(iii) $a<0$ 일 때 $P^{C}= left{x left| 2a le x le -a right. right}$ 이므로 $2a ge -4$ , $-a le 6$ 에서 $-2 le a<0$",
      "따라서 $-2 le a le 3$ 이므로 $M=3$ , $m=-2$ , $Mm=-6$"]),

dict(no=8, unit="도형의 방정식", level="중상", src="2026-3월 14번", point="대칭이동을 이용한 거리의 최솟값",
 body=["그림과 같이 좌표평면 위에 원 $C`:` left(x-10 right)^{2}+ left(y-6 right)^{2}=5$ 와 점 ${rm{A}} left(1,`0 right)$ 이 있다. 원 $C$ 위의 점 ${rm{P}}$ , 직선 $y=x$ 위의 점 ${rm{Q}}$ 에 대하여 ${ bar{rm{AQ}}} + { bar{rm{QP}}}$ 의 최솟값은?"],
 fig="reflect.png",
 choices=["3 sqrt{5}", "4 sqrt{5}", "5 sqrt{5}", "6 sqrt{5}", "7 sqrt{5}"], ans=2,
 sol=["점 ${rm{A}}$ 를 직선 $y=x$ 에 대하여 대칭이동한 점을 ${rm{A}} prime$ 이라 하면 ${rm{A}} prime left(0,`1 right)$ 이고 ${ bar{rm{AQ}}} = { bar{{rm{A}} prime {rm{Q}}}}$",
      "${ bar{rm{AQ}}} + { bar{rm{QP}}} = { bar{{rm{A}} prime {rm{Q}}}} + { bar{rm{QP}}} ge { bar{{rm{A}} prime {rm{P}}}}$",
      "원의 중심 $left(10,`6 right)$ 과 ${rm{A}} prime$ 사이의 거리는 $sqrt{100+25} =5 sqrt{5}$ 이므로 ${ bar{{rm{A}} prime {rm{P}}}}$ 의 최솟값은 $5 sqrt{5} - sqrt{5} =4 sqrt{5}$",
      "점 ${rm{A}} prime$ 과 원 $C$ 는 직선 $y=x$ 에 대하여 서로 반대쪽에 있으므로 이때의 선분 ${rm{A}} prime {rm{P}}$ 는 직선 $y=x$ 와 만난다. 따라서 구하는 최솟값은 $4 sqrt{5}$"]),

dict(no=9, unit="함수와 그래프", level="중상", src="2024-3월 12번", point="일대일대응이 되기 위한 조건",
 body=["실수 전체의 집합에서 정의된 함수",
       "$f left(x right)= cases{ left(a+4 right)x+3 && left(x<2 right) # left(6-a right)x+4a-1 && left(x ge 2 right) }$",
       "의 역함수가 존재하도록 하는 모든 정수 $a$ 의 개수는?"],
 choices=["6", "7", "8", "9", "10"], ans=4,
 sol=["$x=2$ 에서 두 식의 값은 모두 $2a+11$ 이므로 $y=f left(x right)$ 의 그래프는 점 $left(2,`2a+11 right)$ 에서 이어져 있다.",
      "역함수가 존재하려면 $f$ 가 일대일대응이어야 하므로 두 직선의 기울기의 부호가 같아야 한다.",
      "$left(a+4 right) left(6-a right)>0$ 에서 $-4<a<6$",
      "따라서 정수 $a$ 는 $-3,`-2,`CDOTS,`5$ 의 $9$ 개"]),

dict(no=10, unit="함수와 그래프", level="상", src="2025-3월 14번", point="유리함수의 그래프와 최댓값",
 body=["$0 le x le 2$ 에서 함수 $f left(x right)={2x+k} over {x-3}$ 의 최댓값이 $4$ 가 되도록 하는 상수 $k$ 의 값은?"],
 choices=["-11", "-10", "-9", "-8", "-7"], ans=4,
 sol=["$f left(x right)=2+ {k+6} over {x-3}$",
      "(i) $k+6>0$ 이면 $0 le x le 2$ 에서 감소하므로 최댓값은 $f left(0 right)=2- {k+6} over {3} =4$ 에서 $k=-12$ 인데 $k+6>0$ 에 모순",
      "(ii) $k+6<0$ 이면 증가하므로 최댓값은 $f left(2 right)=2- left(k+6 right)=4$ 에서 $k=-8$ (조건 만족)",
      "(iii) $k+6=0$ 이면 $f left(x right)=2$ 이므로 성립하지 않는다.",
      "따라서 $k=-8$"]),

dict(no=11, unit="도형의 방정식", level="상", src="2025-10월 14번", point="평행이동과 대칭이동을 이용한 거리의 최솟값",
 body=["좌표평면 위에 두 점 ${rm{A}} left(-4,`3 right)$ , ${rm{B}} left(4,`5 right)$ 가 있다. ${ bar{rm{PQ}}} =2$ 인 $x$ 축 위의 두 점 ${rm{P}}$ , ${rm{Q}}$ 에 대하여 ${ bar{rm{AP}}} + { bar{rm{QB}}}$ 의 최솟값은? (단, 점 ${rm{P}}$ 의 $x$ 좌표는 점 ${rm{Q}}$ 의 $x$ 좌표보다 작다.)"],
 choices=["8", "6 sqrt{2}", "2 sqrt{21}", "4 sqrt{6}", "10"], ans=5,
 sol=["${rm{P}} left(t,`0 right)$ 이면 ${rm{Q}} left(t+2,`0 right)$ 이다. 점 ${rm{A}}$ 를 $x$ 축의 방향으로 $2$ 만큼 평행이동한 점을 ${rm{C}} left(-2,`3 right)$ 이라 하면 ${ bar{rm{AP}}} = { bar{rm{CQ}}}$",
      "점 ${rm{C}}$ 를 $x$ 축에 대하여 대칭이동한 점을 ${rm{D}} left(-2,`-3 right)$ 이라 하면 ${ bar{rm{CQ}}} = { bar{rm{DQ}}}$",
      "${ bar{rm{AP}}} + { bar{rm{QB}}} = { bar{rm{DQ}}} + { bar{rm{QB}}} ge { bar{rm{DB}}} = sqrt{6^{2}+8^{2}} =10$",
      "점 ${rm{Q}}$ 가 선분 ${rm{DB}}$ 와 $x$ 축의 교점일 때 등호가 성립하므로 구하는 최솟값은 $10$"]),

dict(no=12, unit="함수와 그래프", level="상", src="2026-3월 12번", point="무리함수와 역함수의 그래프의 교점",
 body=["그림과 같이 함수 $f left(x right)=3 sqrt{x}$ 의 그래프와 함수 $g left(x right)={1} over {9} x^{2}~ left(x ge 0 right)$ 의 그래프가 만나는 두 점 중 원점 ${rm{O}}$ 가 아닌 점을 ${rm{A}}$ 라 하고, 선분 ${rm{OA}}$ 를 $4`:`5$ 로 내분하는 점을 ${rm{P}}$ 라 하자. 점 ${rm{P}}$ 를 지나고 $x$ 축에 평행한 직선이 두 곡선 $y=f left(x right)$ , $y=g left(x right)$ 와 만나는 점을 각각 ${rm{B}}$ , ${rm{C}}$ 라 할 때, 삼각형 ${rm{ABC}}$ 의 넓이는?"],
 fig="twocurve.png",
 choices=["{89} over {9}", "{92} over {9}", "{95} over {9}", "{98} over {9}", "{101} over {9}"], ans=3,
 sol=["$3 sqrt{x} = {1} over {9} x^{2}$ 에서 $x^{4}=729x$ , $x left(x^{3}-729 right)=0$ 이므로 ${rm{A}} left(9,`9 right)$",
      "${rm{P}}$ 는 선분 ${rm{OA}}$ 를 $4`:`5$ 로 내분하므로 ${rm{P}} left(4,`4 right)$",
      "$3 sqrt{x} =4$ 에서 $x= {16} over {9}$ 이므로 ${rm{B}} left({16} over {9},`4 right)$ , ${1} over {9} x^{2}=4$ 에서 $x=6$ 이므로 ${rm{C}} left(6,`4 right)$",
      "${ bar{rm{BC}}} =6- {16} over {9} = {38} over {9}$ 이고 높이는 $9-4=5$ 이므로 넓이는 ${1} over {2} TIMES {38} over {9} TIMES 5= {95} over {9}$"]),

dict(no=13, unit="도형의 방정식", level="최상", src="2026-3월 17번", point="원과 직선의 위치 관계와 거리 비",
 body=["그림과 같이 좌표평면 위에 원 $C`:` left(x-4 right)^{2}+ left(y-2 right)^{2}=4$ 와 직선 $y=mx~ left(0<m<1 right)$ 이 있다. 원 $C$ 의 중심을 ${rm{A}}$ , 점 ${rm{A}}$ 에서 직선 $y=mx$ 에 내린 수선의 발을 ${rm{H}}$ , 직선 $y=mx$ 가 원 $C$ 와 만나는 두 점 중 원점 ${rm{O}}$ 에 가까운 점을 ${rm{B}}$ 라 할 때, ${ bar{rm{OH}}} `:` { bar{rm{BH}}} =3`:`1$ 이다. 상수 $m$ 의 값은?"],
 fig="circleline.png",
 choices=["{1} over {7}", "{1} over {6}", "{1} over {5}", "{1} over {4}", "{1} over {3}"], ans=1,
 sol=["${ bar{rm{AH}}} =d$ 라 하면 ${ bar{rm{OA}}}^{2} =16+4=20$ 이므로 ${ bar{rm{OH}}}^{2} =20-d^{2}$ , ${ bar{rm{BH}}}^{2} =4-d^{2}$",
      "${ bar{rm{OH}}} =3 { bar{rm{BH}}}$ 이므로 $20-d^{2}=9 left(4-d^{2} right)$ , $d^{2}=2$",
      "점 ${rm{A}} left(4,`2 right)$ 와 직선 $mx-y=0$ 사이의 거리에서 ${ left(4m-2 right)^{2}} over {m^{2}+1} =2$",
      "$7m^{2}-8m+1=0$ , $left(7m-1 right) left(m-1 right)=0$",
      "$0<m<1$ 이므로 $m= {1} over {7}$"]),

dict(no=14, unit="도형의 방정식", level="최상", src="2024-3월 21번", point="원의 접선의 성질과 대칭을 이용한 도형의 추론",
 body=["그림과 같이 두 직선 $l_{1}`:`y=mx~ left(m>1 right)$ 과 $l_{2}`:`y={1} over {m}x$ 에 동시에 접하는 원의 중심을 ${rm{A}}$ 라 하자. 직선 $l_{1}$ 과 원의 접점을 ${rm{P}}$ , 직선 $l_{2}$ 와 원의 접점을 ${rm{Q}}$ , 직선 ${rm{PQ}}$ 가 $x$ 축과 만나는 점을 ${rm{R}}$ 이라 할 때, 세 점 ${rm{P}}$ , ${rm{Q}}$ , ${rm{R}}$ 이 다음 조건을 만족시킨다."],
 box=["(가) ${ bar{rm{PQ}}} `:` { bar{rm{QR}}} =2`:`1$",
      "(나) 삼각형 ${rm{OPQ}}$ 의 넓이는 $16$ 이다."],
 body2=["직선 $l_{1}$ 과 직선 ${rm{AQ}}$ 의 교점을 ${rm{B}}$ 라 할 때, 선분 ${rm{BQ}}$ 의 길이는? (단, 원의 중심 ${rm{A}}$ 는 제 $1$ 사분면 위에 있고, ${rm{O}}$ 는 원점이다.)"],
 fig="tangent2.png", figlast=True,
 choices=["{8} over {3} sqrt{10}", "3 sqrt{10}", "{10} over {3} sqrt{10}", "{11} over {3} sqrt{10}", "4 sqrt{10}"], ans=1,
 sol=["두 직선 $l_{1}$ , $l_{2}$ 는 직선 $y=x$ 에 대하여 대칭이고 원의 중심 ${rm{A}}$ 는 직선 $y=x$ 위에 있으므로 두 접점 ${rm{P}}$ , ${rm{Q}}$ 도 직선 $y=x$ 에 대하여 대칭이다.",
      "${rm{Q}} left(s,`t right)$ 라 하면 ${rm{P}} left(t,`s right)$ 이고, 직선 ${rm{PQ}}$ 의 기울기는 $-1$ 이므로 ${rm{R}} left(s+t,`0 right)$",
      "(가)에서 점 ${rm{Q}}$ 는 선분 ${rm{PR}}$ 을 $2`:`1$ 로 내분하므로 $t={s} over {3}$ , 즉 ${rm{Q}} left(3t,`t right)$ , ${rm{P}} left(t,`3t right)$ 이고 $m=3$",
      "(나)에서 삼각형 ${rm{OPQ}}$ 의 넓이는 ${1} over {2} left| 3t TIMES 3t-t TIMES t right| =4t^{2}=16$ 이므로 $t=2$ , ${rm{Q}} left(6,`2 right)$",
      "직선 ${rm{AQ}}$ 는 점 ${rm{Q}}$ 를 지나고 $l_{2}$ 에 수직이므로 $y=-3x+20$ 이고, $l_{1}`:`y=3x$ 와의 교점은 ${rm{B}} left({10} over {3},`10 right)$",
      "따라서 ${ bar{rm{BQ}}} = sqrt{ left(6-{10} over {3} right)^{2}+ left(2-10 right)^{2}} = sqrt{{640} over {9}} ={8} over {3} sqrt{10}$"]),

dict(no=15, unit="집합과 명제", level="중상", src="2024-3월 26번", point="명제가 참이 되기 위한 조건과 이차부등식",
 body=["실수 $x$ 에 대한 두 조건",
       "$p`:`2x-a=0$ , $q`:`x^{2}-2bx+3b>0$",
       "이 있다. 명제 $p rarrow ~ sim q$ 와 명제 $~ sim p rarrow q$ 가 모두 참이 되도록 하는 두 양수 $a$ , $b$ 에 대하여 $a+b$ 의 값을 구하시오."],
 choices=None, ans=9,
 sol=["$p$ 의 진리집합은 $left{ {a} over {2} right}$ 이다.",
      "명제 $~ sim p rarrow q$ 가 참이므로 $x ne {a} over {2}$ 인 모든 실수 $x$ 에 대하여 $x^{2}-2bx+3b>0$",
      "명제 $p rarrow ~ sim q$ 가 참이므로 $x={a} over {2}$ 일 때 $x^{2}-2bx+3b le 0$",
      "따라서 $x^{2}-2bx+3b= left(x-{a} over {2} right)^{2}$ 이어야 하므로 $b^{2}-3b=0$ 이고, $b>0$ 이므로 $b=3$",
      "이때 $x^{2}-6x+9= left(x-3 right)^{2}$ 이므로 ${a} over {2} =3$ , $a=6$ 이고 $a+b=9$"]),

dict(no=16, unit="도형의 방정식", level="중상", src="2025-10월 28번", point="원과 좌표축의 교점, 원과 직선이 접할 조건",
 body=["원 $O$ 가 $x$ 축과 두 점 ${rm{A}}$ , ${rm{B}}$ 에서 만나고, $y$ 축과 두 점 ${rm{C}}$ , ${rm{D}}$ 에서 만난다. 네 점 ${rm{A}}$ , ${rm{B}}$ , ${rm{C}}$ , ${rm{D}}$ 와 원 $O$ 가 다음 조건을 만족시킬 때, 사각형 ${rm{ACBD}}$ 의 넓이를 구하시오. (단, 점 ${rm{A}}$ 의 $x$ 좌표는 점 ${rm{B}}$ 의 $x$ 좌표보다 작고, 점 ${rm{C}}$ 의 $y$ 좌표는 점 ${rm{D}}$ 의 $y$ 좌표보다 작다.)"],
 box=["(가) 선분 ${rm{AB}}$ 를 $1`:`4$ 로 내분하는 점은 선분 ${rm{CD}}$ 의 중점이다.",
      "(나) 원 $O$ 가 직선 $4x+3y+26=0$ 에 접한다."],
 choices=None, ans=160,
 sol=["원 $O$ 의 중심을 $left(h,`k right)$ , 반지름의 길이를 $r$ 라 하면 선분 ${rm{CD}}$ 의 중점은 $left(0,`k right)$ 이고, 선분 ${rm{AB}}$ 를 내분하는 점은 $x$ 축 위에 있으므로 (가)에서 $k=0$",
      "${rm{A}} left(h-r,`0 right)$ , ${rm{B}} left(h+r,`0 right)$ 이므로 내분하는 점의 $x$ 좌표는 $h-r+{2r} over {5} =0$ , 즉 $h={3} over {5}r$",
      "(나)에서 ${left| {12} over {5}r+26 right|} over {5} =r$ 이고 $r>0$ 이므로 ${12} over {5}r+26=5r$ , $r=10$",
      "$h=6$ 이므로 ${ bar{rm{AB}}} =20$ , ${ bar{rm{CD}}} =2 sqrt{100-36} =16$",
      "사각형 ${rm{ACBD}}$ 의 두 대각선은 서로 수직이므로 넓이는 ${1} over {2} TIMES 20 TIMES 16=160$"]),

dict(no=17, unit="함수와 그래프", level="중상", src="2024-3월 27번", point="조건을 만족시키는 함수의 개수",
 body=["집합 $X= left{1,`2,`3,`4,`5,`6 right}$ 에 대하여 다음 조건을 만족시키는 함수 $f`:`X rarrow X$ 의 개수를 구하시오."],
 box=["(가) $x_{1} in X$ , $x_{2} in X$ 인 임의의 $x_{1}$ , $x_{2}$ 에 대하여 $1 le x_{1} < x_{2} le 4$ 이면 $f left(x_{1} right) > f left(x_{2} right)$ 이다.",
      "(나) $f left(5 right) < f left(6 right)$ 이다.",
      "(다) 함수 $f$ 의 역함수가 존재하지 않는다."],
 choices=None, ans=210,
 sol=["(가)에서 $f left(1 right)>f left(2 right)>f left(3 right)>f left(4 right)$ 이므로 이 네 값을 정하는 방법은 ${}_{6} rm C _{4} =15$ 가지",
      "(나)에서 $f left(5 right)$ , $f left(6 right)$ 를 정하는 방법은 ${}_{6} rm C _{2} =15$ 가지이므로 (가), (나)를 만족시키는 함수는 $15 TIMES 15=225$ 개",
      "이 중 역함수가 존재하는 함수는 $f left(5 right)$ , $f left(6 right)$ 가 남은 두 수이고 $f left(5 right)<f left(6 right)$ 인 경우이므로 $15 TIMES 1=15$ 개",
      "따라서 구하는 함수의 개수는 $225-15=210$"]),

dict(no=18, unit="집합과 명제", level="상", src="2024-3월 28번", point="집합의 연산과 원소의 개수",
 body=["$1$ 보다 큰 자연수 $k$ 에 대하여 전체집합",
       "$U= left{x left| x 는~ k ~이하의~자연수 right. right}$",
       "의 두 부분집합",
       "$A= left{x left| x 는~ k ~이하의~짝수 right. right}$ , $B= left{x left| x 는~ k 의~약수 right. right}$",
       "가 $n left(A right) TIMES n left( left(A cup B right)^{C} right)=28$ 을 만족시킨다. 집합 $left(A cup B right)^{C}$ 의 모든 원소의 합을 구하시오."],
 choices=None, ans=40,
 sol=["$left(A cup B right)^{C}$ 는 $k$ 이하의 홀수 중 $k$ 의 약수가 아닌 수의 집합이고, $1$ 은 항상 $k$ 의 약수이다.",
      "$k$ 이하의 짝수의 개수를 $n$ 이라 하면 $k$ 이하의 홀수는 $n$ 개 또는 $n+1$ 개이고, $k$ 가 홀수이면 $k$ 자신도 약수이므로 $n left( left(A cup B right)^{C} right) le n-1<n left(A right)$",
      "따라서 $left(n left(A right),`n left( left(A cup B right)^{C} right) right)$ 는 $left(7,`4 right)$ , $left(14,`2 right)$ , $left(28,`1 right)$ 중 하나이다.",
      "(i) $n left(A right)=7$ 이면 $k=14$ 또는 $k=15$ 이다. $k=14$ 이면 $left(A cup B right)^{C}= left{3,`5,`9,`11,`13 right}$ , $k=15$ 이면 $left(A cup B right)^{C}= left{7,`9,`11,`13 right}$ 이므로 $k=15$",
      "(ii) $n left(A right)=14$ 이면 $k=28$ 또는 $29$ 이고 $n left( left(A cup B right)^{C} right)$ 는 각각 $12$ , $13$ 이므로 성립하지 않는다. 같은 방법으로 $n left(A right)=28$ 인 경우도 성립하지 않는다.",
      "따라서 구하는 합은 $7+9+11+13=40$"]),

dict(no=19, unit="집합과 명제", level="최상", src="2026-3월 19번", point="조건을 만족시키는 집합의 추론",
 body=["집합 $X= left{1,`2,`3,`4,`5,`6,`7,`8,`9,`10 right}$ 이 있다. 다음 조건을 만족시키는 집합 $X$ 의 두 부분집합 $A$ , $B$ 에 대하여 집합 $B-A$ 의 모든 원소의 합의 최댓값을 구하시오."],
 box=["(가) $n left(A cap B right)=2$ , $n left(B-A right)=3$",
      "(나) $p in A cap B$ 이면 ${p+1} over {2} in B-A$ 이다.",
      "(다) $q in B-A$ 이면 $q+3 in A$ 이다."],
 choices=None, ans=15,
 sol=["(다)에서 $B-A$ 의 원소 $q$ 는 $q+3 le 10$ , 즉 $q le 7$ 이다.",
      "(나)에서 $A cap B$ 의 원소 $p$ 는 $10$ 이하의 홀수이므로 ${p+1} over {2} le 5$ 이고, 서로 다른 두 원소 $p$ 에 대하여 ${p+1} over {2}$ 는 $B-A$ 의 서로 다른 두 원소이다.",
      "따라서 $B-A$ 는 $5$ 이하의 원소를 $2$ 개 이상 가지므로 원소의 합은 $4+5+7=16$ 이하이다.",
      "합이 $16$ 이면 $B-A= left{4,`5,`7 right}$ 이고 $A cap B= left{7,`9 right}$ 이어야 하는데, $7$ 이 $A cap B$ 와 $B-A$ 에 동시에 속하므로 모순이다.",
      "$A cap B= left{7,`9 right}$ , $B-A= left{4,`5,`6 right}$ 이면 (다)에서 $7,`8,`9 in A$ 이므로 $A= left{7,`8,`9 right}$ , $B= left{4,`5,`6,`7,`9 right}$ 로 모든 조건을 만족시킨다.",
      "따라서 최댓값은 $4+5+6=15$"]),

dict(no=20, unit="함수와 그래프", level="최상", pts=7, src="2024-3월 30번", point="무리함수의 그래프와 교점의 개수의 추론",
 body=["두 상수 $a$ , $b$ 에 대하여 함수 $f left(x right)= sqrt{-x+a} -b$ 라 하자. 함수",
       "$g left(x right)= cases{ left| f left(x right) right| +b && left(x le a right) # -f left(-x+2a right)+ left| b right| && left(x>a right) }$",
       "와 두 실수 $alpha$ , $beta ~ left( alpha < beta right)$ 는 다음 조건을 만족시킨다."],
 box=["(가) 실수 $t$ 에 대하여 함수 $y=g left(x right)$ 의 그래프와 직선 $y=t$ 의 교점의 개수를 $h left(t right)$ 라 하면 $h left( alpha right) TIMES h left( beta right)=4$ 이다.",
      "(나) 방정식 $left{g left(x right)- alpha right} left{g left(x right)- beta right}=0$ 을 만족시키는 실수 $x$ 의 최솟값은 $-55$ , 최댓값은 $25$ 이다."],
 body2=["$g left(-91 right)-g left(130 right)$ 의 값을 구하시오."],
 choices=None, ans=13,
 sol=["$f left(x right)= sqrt{a-x} -b$ 이고, $x>a$ 일 때 $g left(x right)=- sqrt{x-a} +b+ left| b right|$ 이다.",
      "$b le 0$ 이면 $x le a$ 일 때 $g left(x right)= sqrt{a-x}$ , $x>a$ 일 때 $g left(x right)=- sqrt{x-a}$ 이므로 $h left(t right)=1$ 이 되어 (가)에 모순이다. 따라서 $b>0$",
      "$b>0$ 이면 $x le a$ 에서 $g left(x right)= left| sqrt{a-x} -b right| +b$ 는 $x=a-b^{2}$ 에서 최솟값 $b$ 를 갖고 $x=a$ 에서 $2b$ 이며, $x>a$ 에서 $g left(x right)=- sqrt{x-a} +2b$ 는 $2b$ 보다 작은 값을 가지며 감소한다.",
      "따라서 $h left(t right)$ 는 $t>2b$ 일 때 $1$ , $t=2b$ 일 때 $2$ , $b<t<2b$ 일 때 $3$ , $t=b$ 일 때 $2$ , $t<b$ 일 때 $1$ 이고, (가)에서 $alpha =b$ , $beta =2b$",
      "$g left(x right)=b$ 의 해는 $x=a-b^{2}$ , $a+b^{2}$ 이고, $g left(x right)=2b$ 의 해는 $x=a-4b^{2}$ , $a$ 이므로 (나)에서 $a-4b^{2}=-55$ , $a+b^{2}=25$",
      "$b^{2}=16$ 에서 $b=4$ , $a=9$",
      "$g left(-91 right)= left| sqrt{100} -4 right| +4=10$ , $g left(130 right)=- sqrt{121} +8=-3$ 이므로 구하는 값은 $10- left(-3 right)=13$"]),
]
